static const char *ClassId    = "$Id:  $";
static const char *TagName    = "$Name:  $";
static const char *CvsPath    = "$Source:  $";
static const char *SvnPath    = "$HeadURL: $";
static const char *HttpServer = "http://www.esrf.fr/computing/cs/tango/tango_doc/ds_doc/";
//+=============================================================================
//
// file :        FitGaussianClass.cpp
//
// description : C++ source for the FitGaussianClass. A singleton
//               class derived from DeviceClass. It implements the
//               command list and all properties and methods required
//               by the FitGaussian once per process.
//
// project :     TANGO Device Server
//
// $Author:  $
//
// $Revision:  $
//
// $Log:  $
//
// copyleft :   European Synchrotron Radiation Facility
//              BP 220, Grenoble 38043
//              FRANCE
//
//-=============================================================================
//
//  		This file is generated by POGO
//	(Program Obviously used to Generate tango Object)
//
//         (c) - Software Engineering Group - ESRF
//=============================================================================


#include <tango.h>

#include <FitGaussian.h>
#include <FitGaussianClass.h>


//+----------------------------------------------------------------------------
/**
 *	Create FitGaussianClass singleton and return it in a C function for Python usage
 */
//+----------------------------------------------------------------------------
extern "C" {
#ifdef WIN32

__declspec(dllexport)

#endif

	Tango::DeviceClass *_create_FitGaussian_class(const char *name) {
		return FitGaussian_ns::FitGaussianClass::init(name);
	}
}


namespace FitGaussian_ns
{




//
//----------------------------------------------------------------
//	Initialize pointer for singleton pattern
//----------------------------------------------------------------
//
FitGaussianClass *FitGaussianClass::_instance = NULL;

//+----------------------------------------------------------------------------
//
// method : 		FitGaussianClass::FitGaussianClass(string &s)
// 
// description : 	constructor for the FitGaussianClass
//
// in : - s : The class name
//
//-----------------------------------------------------------------------------
FitGaussianClass::FitGaussianClass(string &s):DeviceClass(s)
{

	cout2 << "Entering FitGaussianClass constructor" << endl;
	set_default_property();
	get_class_property();
	write_class_property();
	
	cout2 << "Leaving FitGaussianClass constructor" << endl;

}
//+----------------------------------------------------------------------------
//
// method : 		FitGaussianClass::~FitGaussianClass()
// 
// description : 	destructor for the FitGaussianClass
//
//-----------------------------------------------------------------------------
FitGaussianClass::~FitGaussianClass()
{
	_instance = NULL;
}

//+----------------------------------------------------------------------------
//
// method : 		FitGaussianClass::instance
// 
// description : 	Create the object if not already done. Otherwise, just
//			return a pointer to the object
//
// in : - name : The class name
//
//-----------------------------------------------------------------------------
FitGaussianClass *FitGaussianClass::init(const char *name)
{
	if (_instance == NULL)
	{
		try
		{
			string s(name);
			_instance = new FitGaussianClass(s);
		}
		catch (bad_alloc)
		{
			throw;
		}		
	}		
	return _instance;
}

FitGaussianClass *FitGaussianClass::instance()
{
	if (_instance == NULL)
	{
		cerr << "Class is not initialised !!" << endl;
		exit(-1);
	}
	return _instance;
}

//+----------------------------------------------------------------------------
//
// method : 		FitGaussianClass::command_factory
// 
// description : 	Create the command object(s) and store them in the 
//			command list
//
//-----------------------------------------------------------------------------
void FitGaussianClass::command_factory()
{

	//	add polling if any
	for (unsigned int i=0 ; i<command_list.size(); i++)
	{
	}
}

//+----------------------------------------------------------------------------
//
// method : 		FitGaussianClass::get_class_property
// 
// description : 	Get the class property for specified name.
//
// in :		string	name : The property name
//
//+----------------------------------------------------------------------------
Tango::DbDatum FitGaussianClass::get_class_property(string &prop_name)
{
	for (unsigned int i=0 ; i<cl_prop.size() ; i++)
		if (cl_prop[i].name == prop_name)
			return cl_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}
//+----------------------------------------------------------------------------
//
// method : 		FitGaussianClass::get_default_device_property()
// 
// description : 	Return the default value for device property.
//
//-----------------------------------------------------------------------------
Tango::DbDatum FitGaussianClass::get_default_device_property(string &prop_name)
{
	for (unsigned int i=0 ; i<dev_def_prop.size() ; i++)
		if (dev_def_prop[i].name == prop_name)
			return dev_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}

//+----------------------------------------------------------------------------
//
// method : 		FitGaussianClass::get_default_class_property()
// 
// description : 	Return the default value for class property.
//
//-----------------------------------------------------------------------------
Tango::DbDatum FitGaussianClass::get_default_class_property(string &prop_name)
{
	for (unsigned int i=0 ; i<cl_def_prop.size() ; i++)
		if (cl_def_prop[i].name == prop_name)
			return cl_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}
//+----------------------------------------------------------------------------
//
// method : 		FitGaussianClass::device_factory
// 
// description : 	Create the device object(s) and store them in the 
//			device list
//
// in :		Tango::DevVarStringArray *devlist_ptr : The device name list
//
//-----------------------------------------------------------------------------
void FitGaussianClass::device_factory(const Tango::DevVarStringArray *devlist_ptr)
{

	//	Create all devices.(Automatic code generation)
	//-------------------------------------------------------------
	for (unsigned long i=0 ; i < devlist_ptr->length() ; i++)
	{
		cout4 << "Device name : " << (*devlist_ptr)[i].in() << endl;
						
		// Create devices and add it into the device list
		//----------------------------------------------------
		device_list.push_back(new FitGaussian(this, (*devlist_ptr)[i]));							 

		// Export device to the outside world
		// Check before if database used.
		//---------------------------------------------
		if ((Tango::Util::_UseDb == true) && (Tango::Util::_FileDb == false))
			export_device(device_list.back());
		else
			export_device(device_list.back(), (*devlist_ptr)[i]);
	}
	//	End of Automatic code generation
	//-------------------------------------------------------------

}
//+----------------------------------------------------------------------------
//	Method: FitGaussianClass::attribute_factory(vector<Tango::Attr *> &att_list)
//-----------------------------------------------------------------------------
void FitGaussianClass::attribute_factory(vector<Tango::Attr *> &att_list)
{
	//	Attribute : version
	versionAttrib	*version = new versionAttrib();
	Tango::UserDefaultAttrProp	version_prop;
	version_prop.set_description("FitGaussian device Version");
	version->set_default_properties(version_prop);
	att_list.push_back(version);

	//	Attribute : operationType
	operationTypeAttrib	*operation_type = new operationTypeAttrib();
	Tango::UserDefaultAttrProp	operation_type_prop;
	operation_type_prop.set_description("Indicates which operation type is applied (NONE or FIT).");
	operation_type->set_default_properties(operation_type_prop);
	att_list.push_back(operation_type);

	//	Attribute : FitEnabled
	FitEnabledAttrib	*fit_enabled = new FitEnabledAttrib();
	Tango::UserDefaultAttrProp	fit_enabled_prop;
	fit_enabled_prop.set_unit(" ");
	fit_enabled_prop.set_description("Enable/Disable Fit Gaussian.");
	fit_enabled->set_default_properties(fit_enabled_prop);
	att_list.push_back(fit_enabled);

	//	Attribute : AutoROIEnabled
	AutoROIEnabledAttrib	*auto_roienabled = new AutoROIEnabledAttrib();
	Tango::UserDefaultAttrProp	auto_roienabled_prop;
	auto_roienabled_prop.set_unit(" ");
	auto_roienabled_prop.set_description("Enable/Disable Auto ROI.");
	auto_roienabled->set_default_properties(auto_roienabled_prop);
	att_list.push_back(auto_roienabled);

	//	Attribute : AutoROIFound
	AutoROIFoundAttrib	*auto_roifound = new AutoROIFoundAttrib();
	Tango::UserDefaultAttrProp	auto_roifound_prop;
	auto_roifound_prop.set_unit(" ");
	auto_roifound_prop.set_description("Indicates whether the automatic ROI detection was successful.");
	auto_roifound->set_default_properties(auto_roifound_prop);
	att_list.push_back(auto_roifound);

	//	Attribute : AutoROIOriginX
	AutoROIOriginXAttrib	*auto_roiorigin_x = new AutoROIOriginXAttrib();
	Tango::UserDefaultAttrProp	auto_roiorigin_x_prop;
	auto_roiorigin_x_prop.set_unit(" ");
	auto_roiorigin_x_prop.set_description("The coordinate of the ROI: OriginX.");
	auto_roiorigin_x->set_default_properties(auto_roiorigin_x_prop);
	att_list.push_back(auto_roiorigin_x);

	//	Attribute : AutoROIOriginY
	AutoROIOriginYAttrib	*auto_roiorigin_y = new AutoROIOriginYAttrib();
	Tango::UserDefaultAttrProp	auto_roiorigin_y_prop;
	auto_roiorigin_y_prop.set_unit(" ");
	auto_roiorigin_y_prop.set_description("The coordinate of the ROI: OriginY.");
	auto_roiorigin_y->set_default_properties(auto_roiorigin_y_prop);
	att_list.push_back(auto_roiorigin_y);

	//	Attribute : AutoROIWidth
	AutoROIWidthAttrib	*auto_roiwidth = new AutoROIWidthAttrib();
	Tango::UserDefaultAttrProp	auto_roiwidth_prop;
	auto_roiwidth_prop.set_unit(" ");
	auto_roiwidth_prop.set_description("The coordinate of the ROI: Width.");
	auto_roiwidth->set_default_properties(auto_roiwidth_prop);
	att_list.push_back(auto_roiwidth);

	//	Attribute : AutoROIHeight
	AutoROIHeightAttrib	*auto_roiheight = new AutoROIHeightAttrib();
	Tango::UserDefaultAttrProp	auto_roiheight_prop;
	auto_roiheight_prop.set_unit(" ");
	auto_roiheight_prop.set_description("The coordinate of the ROI: Height.");
	auto_roiheight->set_default_properties(auto_roiheight_prop);
	att_list.push_back(auto_roiheight);

	//	Attribute : XProjEnabled
	XProjEnabledAttrib	*xproj_enabled = new XProjEnabledAttrib();
	Tango::UserDefaultAttrProp	xproj_enabled_prop;
	xproj_enabled_prop.set_unit(" ");
	xproj_enabled_prop.set_description("Enable/Disable fitting along this axis.");
	xproj_enabled->set_default_properties(xproj_enabled_prop);
	att_list.push_back(xproj_enabled);

	//	Attribute : XProjFitConverged
	XProjFitConvergedAttrib	*xproj_fit_converged = new XProjFitConvergedAttrib();
	Tango::UserDefaultAttrProp	xproj_fit_converged_prop;
	xproj_fit_converged_prop.set_unit(" ");
	xproj_fit_converged_prop.set_description("Indicates whether the projection fitting algorithm has converged along this axis.");
	xproj_fit_converged->set_default_properties(xproj_fit_converged_prop);
	att_list.push_back(xproj_fit_converged);

	//	Attribute : XProjFitCenter
	XProjFitCenterAttrib	*xproj_fit_center = new XProjFitCenterAttrib();
	Tango::UserDefaultAttrProp	xproj_fit_center_prop;
	xproj_fit_center_prop.set_unit(" ");
	xproj_fit_center_prop.set_description("The coordinate of the center of the fitted Gaussian along this axis.");
	xproj_fit_center->set_default_properties(xproj_fit_center_prop);
	att_list.push_back(xproj_fit_center);

	//	Attribute : XProjFitMag
	XProjFitMagAttrib	*xproj_fit_mag = new XProjFitMagAttrib();
	Tango::UserDefaultAttrProp	xproj_fit_mag_prop;
	xproj_fit_mag_prop.set_unit(" ");
	xproj_fit_mag_prop.set_description("The magnitude of  fitted gaussian along this axis.");
	xproj_fit_mag->set_default_properties(xproj_fit_mag_prop);
	att_list.push_back(xproj_fit_mag);

	//	Attribute : XProjFitSigma
	XProjFitSigmaAttrib	*xproj_fit_sigma = new XProjFitSigmaAttrib();
	Tango::UserDefaultAttrProp	xproj_fit_sigma_prop;
	xproj_fit_sigma_prop.set_unit(" ");
	xproj_fit_sigma_prop.set_description("The standard deviation of the fitted Gaussian along this axis.");
	xproj_fit_sigma->set_default_properties(xproj_fit_sigma_prop);
	att_list.push_back(xproj_fit_sigma);

	//	Attribute : XProjFitFWHM
	XProjFitFWHMAttrib	*xproj_fit_fwhm = new XProjFitFWHMAttrib();
	Tango::UserDefaultAttrProp	xproj_fit_fwhm_prop;
	xproj_fit_fwhm_prop.set_unit(" ");
	xproj_fit_fwhm_prop.set_description("The full width at half maximum of the fitted Gaussian along this axis, calculated as approximately 2.35 × the fitted Gaussian standard deviation.");
	xproj_fit_fwhm->set_default_properties(xproj_fit_fwhm_prop);
	att_list.push_back(xproj_fit_fwhm);

	//	Attribute : XProjFitBG
	XProjFitBGAttrib	*xproj_fit_bg = new XProjFitBGAttrib();
	Tango::UserDefaultAttrProp	xproj_fit_bg_prop;
	xproj_fit_bg_prop.set_unit(" ");
	xproj_fit_bg_prop.set_description("The background of  fitted gaussian along this axis.");
	xproj_fit_bg->set_default_properties(xproj_fit_bg_prop);
	att_list.push_back(xproj_fit_bg);

	//	Attribute : XProjFitChi2
	XProjFitChi2Attrib	*xproj_fit_chi2 = new XProjFitChi2Attrib();
	Tango::UserDefaultAttrProp	xproj_fit_chi2_prop;
	xproj_fit_chi2_prop.set_unit(" ");
	xproj_fit_chi2_prop.set_description("The chi2 of the fitted Gaussian along this axis.");
	xproj_fit_chi2->set_default_properties(xproj_fit_chi2_prop);
	att_list.push_back(xproj_fit_chi2);

	//	Attribute : XProjFitNbIter
	XProjFitNbIterAttrib	*xproj_fit_nb_iter = new XProjFitNbIterAttrib();
	Tango::UserDefaultAttrProp	xproj_fit_nb_iter_prop;
	xproj_fit_nb_iter_prop.set_unit(" ");
	xproj_fit_nb_iter_prop.set_description("The number of iterations used for fitting along this axis.");
	xproj_fit_nb_iter->set_default_properties(xproj_fit_nb_iter_prop);
	att_list.push_back(xproj_fit_nb_iter);

	//	Attribute : XProjPushTime
	XProjPushTimeAttrib	*xproj_push_time = new XProjPushTimeAttrib();
	Tango::UserDefaultAttrProp	xproj_push_time_prop;
	xproj_push_time_prop.set_unit(" ");
	xproj_push_time_prop.set_description("The Timestamp at which the sigma value was pushed for this axis.");
	xproj_push_time->set_default_properties(xproj_push_time_prop);
	att_list.push_back(xproj_push_time);

	//	Attribute : YProjEnabled
	YProjEnabledAttrib	*yproj_enabled = new YProjEnabledAttrib();
	Tango::UserDefaultAttrProp	yproj_enabled_prop;
	yproj_enabled_prop.set_unit(" ");
	yproj_enabled_prop.set_description("Enable/Disable fitting along this axis.");
	yproj_enabled->set_default_properties(yproj_enabled_prop);
	att_list.push_back(yproj_enabled);

	//	Attribute : YProjFitConverged
	YProjFitConvergedAttrib	*yproj_fit_converged = new YProjFitConvergedAttrib();
	Tango::UserDefaultAttrProp	yproj_fit_converged_prop;
	yproj_fit_converged_prop.set_unit(" ");
	yproj_fit_converged_prop.set_description("Indicates whether the projection fitting algorithm has converged along this axis.");
	yproj_fit_converged->set_default_properties(yproj_fit_converged_prop);
	att_list.push_back(yproj_fit_converged);

	//	Attribute : YProjFitCenter
	YProjFitCenterAttrib	*yproj_fit_center = new YProjFitCenterAttrib();
	Tango::UserDefaultAttrProp	yproj_fit_center_prop;
	yproj_fit_center_prop.set_unit(" ");
	yproj_fit_center_prop.set_description("The coordinate of the center of the fitted Gaussian along this axis.");
	yproj_fit_center->set_default_properties(yproj_fit_center_prop);
	att_list.push_back(yproj_fit_center);

	//	Attribute : YProjFitMag
	YProjFitMagAttrib	*yproj_fit_mag = new YProjFitMagAttrib();
	Tango::UserDefaultAttrProp	yproj_fit_mag_prop;
	yproj_fit_mag_prop.set_unit(" ");
	yproj_fit_mag_prop.set_description("The magnitude of  fitted gaussian along this axis.");
	yproj_fit_mag->set_default_properties(yproj_fit_mag_prop);
	att_list.push_back(yproj_fit_mag);

	//	Attribute : YProjFitSigma
	YProjFitSigmaAttrib	*yproj_fit_sigma = new YProjFitSigmaAttrib();
	Tango::UserDefaultAttrProp	yproj_fit_sigma_prop;
	yproj_fit_sigma_prop.set_unit(" ");
	yproj_fit_sigma_prop.set_description("The standard deviation of the fitted Gaussian corresponding along this axis.");
	yproj_fit_sigma->set_default_properties(yproj_fit_sigma_prop);
	att_list.push_back(yproj_fit_sigma);

	//	Attribute : YProjFitFWHM
	YProjFitFWHMAttrib	*yproj_fit_fwhm = new YProjFitFWHMAttrib();
	Tango::UserDefaultAttrProp	yproj_fit_fwhm_prop;
	yproj_fit_fwhm_prop.set_unit(" ");
	yproj_fit_fwhm_prop.set_description("The full width at half maximum of the fitted Gaussian along this axis, calculated as approximately 2.35 × the fitted Gaussian standard deviation.");
	yproj_fit_fwhm->set_default_properties(yproj_fit_fwhm_prop);
	att_list.push_back(yproj_fit_fwhm);

	//	Attribute : YProjFitBG
	YProjFitBGAttrib	*yproj_fit_bg = new YProjFitBGAttrib();
	Tango::UserDefaultAttrProp	yproj_fit_bg_prop;
	yproj_fit_bg_prop.set_unit(" ");
	yproj_fit_bg_prop.set_description("The background of  fitted gaussian along this axis.");
	yproj_fit_bg->set_default_properties(yproj_fit_bg_prop);
	att_list.push_back(yproj_fit_bg);

	//	Attribute : YProjFitChi2
	YProjFitChi2Attrib	*yproj_fit_chi2 = new YProjFitChi2Attrib();
	Tango::UserDefaultAttrProp	yproj_fit_chi2_prop;
	yproj_fit_chi2_prop.set_unit(" ");
	yproj_fit_chi2_prop.set_description("The chi-square of the fitted Gaussian along this axis.");
	yproj_fit_chi2->set_default_properties(yproj_fit_chi2_prop);
	att_list.push_back(yproj_fit_chi2);

	//	Attribute : YProjFitNbIter
	YProjFitNbIterAttrib	*yproj_fit_nb_iter = new YProjFitNbIterAttrib();
	Tango::UserDefaultAttrProp	yproj_fit_nb_iter_prop;
	yproj_fit_nb_iter_prop.set_unit(" ");
	yproj_fit_nb_iter_prop.set_description("The number of iterations used for fitting along this axis.");
	yproj_fit_nb_iter->set_default_properties(yproj_fit_nb_iter_prop);
	att_list.push_back(yproj_fit_nb_iter);

	//	Attribute : YProjPushTime
	YProjPushTimeAttrib	*yproj_push_time = new YProjPushTimeAttrib();
	Tango::UserDefaultAttrProp	yproj_push_time_prop;
	yproj_push_time_prop.set_unit(" ");
	yproj_push_time_prop.set_description("The Timestamp at which the sigma value was pushed for this axis.");
	yproj_push_time->set_default_properties(yproj_push_time_prop);
	att_list.push_back(yproj_push_time);

	//	Attribute : operationList
	operationListAttrib	*operation_list = new operationListAttrib();
	Tango::UserDefaultAttrProp	operation_list_prop;
	operation_list_prop.set_description("Enumerate all FitGaussian active 'post processing' operations on the image.");
	operation_list->set_default_properties(operation_list_prop);
	att_list.push_back(operation_list);

	//	Attribute : XProj
	XProjAttrib	*xproj = new XProjAttrib();
	Tango::UserDefaultAttrProp	xproj_prop;
	xproj_prop.set_description("The mean projection spectrum along this axis, with each point representing the average of all values projected onto this axis.");
	xproj->set_default_properties(xproj_prop);
	att_list.push_back(xproj);

	//	Attribute : XProjFitted
	XProjFittedAttrib	*xproj_fitted = new XProjFittedAttrib();
	Tango::UserDefaultAttrProp	xproj_fitted_prop;
	xproj_fitted_prop.set_description("The Gaussian fit result along this axis.");
	xproj_fitted->set_default_properties(xproj_fitted_prop);
	att_list.push_back(xproj_fitted);

	//	Attribute : YProj
	YProjAttrib	*yproj = new YProjAttrib();
	Tango::UserDefaultAttrProp	yproj_prop;
	yproj_prop.set_description("The mean projection spectrum along this axis, with each point representing the average of all values projected onto this axis.");
	yproj->set_default_properties(yproj_prop);
	att_list.push_back(yproj);

	//	Attribute : YProjFitted
	YProjFittedAttrib	*yproj_fitted = new YProjFittedAttrib();
	Tango::UserDefaultAttrProp	yproj_fitted_prop;
	yproj_fitted_prop.set_description("The Gaussian fit result along this axis.");
	yproj_fitted->set_default_properties(yproj_fitted_prop);
	att_list.push_back(yproj_fitted);

	//	Attribute : ROIImage
	ROIImageAttrib	*roiimage = new ROIImageAttrib();
	Tango::UserDefaultAttrProp	roiimage_prop;
	roiimage_prop.set_description("The image with the ROI detected by AutoRoi.");
	roiimage->set_default_properties(roiimage_prop);
	att_list.push_back(roiimage);

	//	End of Automatic code generation
	//-------------------------------------------------------------
}

//+----------------------------------------------------------------------------
//
// method : 		FitGaussianClass::get_class_property()
// 
// description : 	Read the class properties from database.
//
//-----------------------------------------------------------------------------
void FitGaussianClass::get_class_property()
{
	//	Initialize your default values here (if not done with  POGO).
	//------------------------------------------------------------------

	//	Read class properties from database.(Automatic code generation)
	//------------------------------------------------------------------

	//	Call database and extract values
	//--------------------------------------------
	if (Tango::Util::instance()->_UseDb==true)
		get_db_class()->get_property(cl_prop);
	Tango::DbDatum	def_prop;
	int	i = -1;


	//	End of Automatic code generation
	//------------------------------------------------------------------

}

//+----------------------------------------------------------------------------
//
// method : 	FitGaussianClass::set_default_property
// 
// description: Set default property (class and device) for wizard.
//              For each property, add to wizard property name and description
//              If default value has been set, add it to wizard property and
//              store it in a DbDatum.
//
//-----------------------------------------------------------------------------
void FitGaussianClass::set_default_property()
{
	string	prop_name;
	string	prop_desc;
	string	prop_def;

	vector<string>	vect_data;
	//	Set Default Class Properties
	//	Set Default Device Properties
	prop_name = "FitEnabled";
	prop_desc = "Enable/Disable Fit Gaussian.";
	prop_def  = "false";
	vect_data.clear();
	vect_data.push_back("false");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);

	prop_name = "AutoROIEnabled";
	prop_desc = "Enable/Disable automatic ROI detection: if enabled, the ROI is automatically set to encompass the largest particle in the image.";
	prop_def  = "true";
	vect_data.clear();
	vect_data.push_back("true");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);

	prop_name = "AutoROIMagnificationFactorX";
	prop_desc = "";
	prop_def  = "5.0";
	vect_data.clear();
	vect_data.push_back("5.0");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);

	prop_name = "AutoROIMagnificationFactorY";
	prop_desc = "";
	prop_def  = "1.5";
	vect_data.clear();
	vect_data.push_back("1.5");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);

	prop_name = "PixelSizeX";
	prop_desc = "";
	prop_def  = "5.86";
	vect_data.clear();
	vect_data.push_back("5.86");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);

	prop_name = "PixelSizeY";
	prop_desc = "";
	prop_def  = "5.86";
	vect_data.clear();
	vect_data.push_back("5.86");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);

	prop_name = "OpticalMagnification";
	prop_desc = "";
	prop_def  = "2.55";
	vect_data.clear();
	vect_data.push_back("2.55");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);

	prop_name = "FitNbIterationsMax";
	prop_desc = "";
	prop_def  = "256";
	vect_data.clear();
	vect_data.push_back("256");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);

	prop_name = "FitTolerance";
	prop_desc = "";
	prop_def  = "1.e-6";
	vect_data.clear();
	vect_data.push_back("1.e-6");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);

	prop_name = "MemorizedOperationType";
	prop_desc = "Memorize all operationType declared in the order to process the image.";
	prop_def  = "FIT";
	vect_data.clear();
	vect_data.push_back("FIT");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);

	prop_name = "MemorizedOperationLevel";
	prop_desc = "Memorize all levels associated to the operationType declared in the order to process the image.";
	prop_def  = "1";
	vect_data.clear();
	vect_data.push_back("1");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);

	prop_name = "XProjEnabled";
	prop_desc = "";
	prop_def  = "true";
	vect_data.clear();
	vect_data.push_back("true");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);

	prop_name = "YProjEnabled";
	prop_desc = "";
	prop_def  = "true";
	vect_data.clear();
	vect_data.push_back("true");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);

	prop_name = "ProfileFitFixedBg";
	prop_desc = "";
	prop_def  = "false";
	vect_data.clear();
	vect_data.push_back("false");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);

	prop_name = "RotationAngle";
	prop_desc = "Rotate image before Apply Fit <CR>\nAvailable values :<CR>\n- 0 [default]<CR>\n- 90   or -90<CR>\n- 180 or -180<CR>\n- 270 or -270<CR>";
	prop_def  = "0";
	vect_data.clear();
	vect_data.push_back("0");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);

	prop_name = "DisplayRotatedImage";
	prop_desc = "Enable/Disable dipslaying rotated image into image attribute";
	prop_def  = "true";
	vect_data.clear();
	vect_data.push_back("true");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);

}
//+----------------------------------------------------------------------------
//
// method : 		FitGaussianClass::write_class_property
// 
// description : 	Set class description as property in database
//
//-----------------------------------------------------------------------------
void FitGaussianClass::write_class_property()
{
	//	First time, check if database used
	//--------------------------------------------
	if (Tango::Util::_UseDb == false)
		return;

	Tango::DbData	data;
	string	classname = get_name();
	string	header;
	string::size_type	start, end;

	//	Put title
	Tango::DbDatum	title("ProjectTitle");
	string	str_title("Fit Gaussian");
	title << str_title;
	data.push_back(title);

	//	Put Description
	Tango::DbDatum	description("Description");
	vector<string>	str_desc;
	str_desc.push_back("Compute a Gaussian Fit according to Levenberg Marquardt method");
	description << str_desc;
	data.push_back(description);
		
	//	put cvs or svn location
	string	filename(classname);
	filename += "Class.cpp";
	
	// Create a string with the class ID to
	// get the string into the binary
	string	class_id(ClassId);
	
	// check for cvs information
	string	src_path(CvsPath);
	start = src_path.find("/");
	if (start!=string::npos)
	{
		end   = src_path.find(filename);
		if (end>start)
		{
			string	strloc = src_path.substr(start, end-start);
			//	Check if specific repository
			start = strloc.find("/cvsroot/");
			if (start!=string::npos && start>0)
			{
				string	repository = strloc.substr(0, start);
				if (repository.find("/segfs/")!=string::npos)
					strloc = "ESRF:" + strloc.substr(start, strloc.length()-start);
			}
			Tango::DbDatum	cvs_loc("cvs_location");
			cvs_loc << strloc;
			data.push_back(cvs_loc);
		}
	}
	// check for svn information
	else
	{
		string	src_path(SvnPath);
		start = src_path.find("://");
		if (start!=string::npos)
		{
			end = src_path.find(filename);
			if (end>start)
			{
				header = "$HeadURL: ";
				start = header.length();
				string	strloc = src_path.substr(start, (end-start));
				
				Tango::DbDatum	svn_loc("svn_location");
				svn_loc << strloc;
				data.push_back(svn_loc);
			}
		}
	}

	//	Get CVS or SVN revision tag
	
	// CVS tag
	string	tagname(TagName);
	header = "$Name: ";
	start = header.length();
	string	endstr(" $");
	
	end   = tagname.find(endstr);
	if (end!=string::npos && end>start)
	{
		string	strtag = tagname.substr(start, end-start);
		Tango::DbDatum	cvs_tag("cvs_tag");
		cvs_tag << strtag;
		data.push_back(cvs_tag);
	}
	
	// SVN tag
	string	svnpath(SvnPath);
	header = "$HeadURL: ";
	start = header.length();
	
	end   = svnpath.find(endstr);
	if (end!=string::npos && end>start)
	{
		string	strloc = svnpath.substr(start, end-start);
		
		string tagstr ("/tags/");
		start = strloc.find(tagstr);
		if ( start!=string::npos )
		{
			start = start + tagstr.length();
			end   = strloc.find(filename);
			string	strtag = strloc.substr(start, end-start-1);
			
			Tango::DbDatum	svn_tag("svn_tag");
			svn_tag << strtag;
			data.push_back(svn_tag);
		}
	}

	//	Get URL location
	string	httpServ(HttpServer);
	if (httpServ.length()>0)
	{
		Tango::DbDatum	db_doc_url("doc_url");
		db_doc_url << httpServ;
		data.push_back(db_doc_url);
	}

	//  Put inheritance
	Tango::DbDatum	inher_datum("InheritedFrom");
	vector<string> inheritance;
	inheritance.push_back("Device_4Impl");
	inher_datum << inheritance;
	data.push_back(inher_datum);

	//	Call database and and values
	//--------------------------------------------
	get_db_class()->put_property(data);
}

}	// namespace
