/*----- PROTECTED REGION ID(SlsJungfrauClass.cpp) ENABLED START -----*/
static const char *RcsId      = "$Id:  $";
static const char *TagName    = "$Name:  $";
static const char *CvsPath    = "$Source:  $";
static const char *SvnPath    = "$HeadURL:  $";
static const char *HttpServer = "http://www.esrf.eu/computing/cs/tango/tango_doc/ds_doc/";
//=============================================================================
//
// file :        SlsJungfrauClass.cpp
//
// description : C++ source for the SlsJungfrauClass.
//               A singleton class derived from DeviceClass.
//               It implements the command and attribute list
//               and all properties and methods required
//               by the SlsJungfrau once per process.
//
// project :     Sls dectector TANGO specific device.
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#include <SlsJungfrauClass.h>

/*----- PROTECTED REGION END -----*/	//	SlsJungfrauClass.cpp

//-------------------------------------------------------------------
/**
 *	Create SlsJungfrauClass singleton and
 *	return it in a C function for Python usage
 */
//-------------------------------------------------------------------
extern "C" {
#ifdef _TG_WINDOWS_

__declspec(dllexport)

#endif

	Tango::DeviceClass *_create_SlsJungfrau_class(const char *name) {
		return SlsJungfrau_ns::SlsJungfrauClass::init(name);
	}
}

namespace SlsJungfrau_ns
{
//===================================================================
//	Initialize pointer for singleton pattern
//===================================================================
SlsJungfrauClass *SlsJungfrauClass::_instance = NULL;

//--------------------------------------------------------
/**
 * method : 		SlsJungfrauClass::SlsJungfrauClass(string &s)
 * description : 	constructor for the SlsJungfrauClass
 *
 * @param s	The class name
 */
//--------------------------------------------------------
SlsJungfrauClass::SlsJungfrauClass(string &s):Tango::DeviceClass(s)
{
	cout2 << "Entering SlsJungfrauClass constructor" << endl;
	set_default_property();
	write_class_property();

	/*----- PROTECTED REGION ID(SlsJungfrauClass::constructor) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SlsJungfrauClass::constructor

	cout2 << "Leaving SlsJungfrauClass constructor" << endl;
}

//--------------------------------------------------------
/**
 * method : 		SlsJungfrauClass::~SlsJungfrauClass()
 * description : 	destructor for the SlsJungfrauClass
 */
//--------------------------------------------------------
SlsJungfrauClass::~SlsJungfrauClass()
{
	/*----- PROTECTED REGION ID(SlsJungfrauClass::destructor) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SlsJungfrauClass::destructor

	_instance = NULL;
}


//--------------------------------------------------------
/**
 * method : 		SlsJungfrauClass::init
 * description : 	Create the object if not already done.
 *                  Otherwise, just return a pointer to the object
 *
 * @param	name	The class name
 */
//--------------------------------------------------------
SlsJungfrauClass *SlsJungfrauClass::init(const char *name)
{
	if (_instance == NULL)
	{
		try
		{
			string s(name);
			_instance = new SlsJungfrauClass(s);
		}
		catch (bad_alloc &)
		{
			throw;
		}		
	}		
	return _instance;
}

//--------------------------------------------------------
/**
 * method : 		SlsJungfrauClass::instance
 * description : 	Check if object already created,
 *                  and return a pointer to the object
 */
//--------------------------------------------------------
SlsJungfrauClass *SlsJungfrauClass::instance()
{
	if (_instance == NULL)
	{
		cerr << "Class is not initialised !!" << endl;
		exit(-1);
	}
	return _instance;
}



//===================================================================
//	Command execution method calls
//===================================================================
//--------------------------------------------------------
/**
 * method : 		SetCmdClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *SetCmdClass::execute(Tango::DeviceImpl *device, const CORBA::Any &in_any)
{
	cout2 << "SetCmdClass::execute(): arrived" << endl;
	Tango::DevString argin;
	extract(in_any, argin);
	return insert((static_cast<SlsJungfrau *>(device))->set_cmd(argin));
}

//--------------------------------------------------------
/**
 * method : 		GetCmdClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *GetCmdClass::execute(Tango::DeviceImpl *device, const CORBA::Any &in_any)
{
	cout2 << "GetCmdClass::execute(): arrived" << endl;
	Tango::DevString argin;
	extract(in_any, argin);
	return insert((static_cast<SlsJungfrau *>(device))->get_cmd(argin));
}

//--------------------------------------------------------
/**
 * method : 		ResetCameraClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *ResetCameraClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "ResetCameraClass::execute(): arrived" << endl;
	((static_cast<SlsJungfrau *>(device))->reset_camera());
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		CalibrateClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *CalibrateClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "CalibrateClass::execute(): arrived" << endl;
	((static_cast<SlsJungfrau *>(device))->calibrate());
	return new CORBA::Any();
}


//===================================================================
//	Properties management
//===================================================================
//--------------------------------------------------------
/**
 *	Method      : SlsJungfrauClass::get_class_property()
 *	Description : Get the class property for specified name.
 */
//--------------------------------------------------------
Tango::DbDatum SlsJungfrauClass::get_class_property(string &prop_name)
{
	for (unsigned int i=0 ; i<cl_prop.size() ; i++)
		if (cl_prop[i].name == prop_name)
			return cl_prop[i];
	//	if not found, returns  an empty DbDatum
	return Tango::DbDatum(prop_name);
}

//--------------------------------------------------------
/**
 *	Method      : SlsJungfrauClass::get_default_device_property()
 *	Description : Return the default value for device property.
 */
//--------------------------------------------------------
Tango::DbDatum SlsJungfrauClass::get_default_device_property(string &prop_name)
{
	for (unsigned int i=0 ; i<dev_def_prop.size() ; i++)
		if (dev_def_prop[i].name == prop_name)
			return dev_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}

//--------------------------------------------------------
/**
 *	Method      : SlsJungfrauClass::get_default_class_property()
 *	Description : Return the default value for class property.
 */
//--------------------------------------------------------
Tango::DbDatum SlsJungfrauClass::get_default_class_property(string &prop_name)
{
	for (unsigned int i=0 ; i<cl_def_prop.size() ; i++)
		if (cl_def_prop[i].name == prop_name)
			return cl_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}


//--------------------------------------------------------
/**
 *	Method      : SlsJungfrauClass::set_default_property()
 *	Description : Set default property (class and device) for wizard.
 *                For each property, add to wizard property name and description.
 *                If default value has been set, add it to wizard property and
 *                store it in a DbDatum.
 */
//--------------------------------------------------------
void SlsJungfrauClass::set_default_property()
{
	string	prop_name;
	string	prop_desc;
	string	prop_def;
	vector<string>	vect_data;

	//	Set Default Class Properties

	//	Set Default device Properties
	prop_name = "ConfigFileName";
	prop_desc = "Configuration files used during the camera instanciation.";
	prop_def  = "";
	vect_data.clear();
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "ExpertReadoutTime";
	prop_desc = "Only an expert User could change this property.<br>\nThis is the readout time in seconds of the camera.<BR>";
	prop_def  = "";
	vect_data.clear();
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "ExpertReceiverFifoDepth";
	prop_desc = "Only an expert User could change this property.<br>\nThis is the number of frames in memory of the receiver.<BR>";
	prop_def  = "";
	vect_data.clear();
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "ExpertFramePacketNumber";
	prop_desc = "Only an expert User could change this property.<br>\nThis is the number of packet for each received frame part.<BR>";
	prop_def  = "";
	vect_data.clear();
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "ExpertGainsCoeffsFileName";
	prop_desc = "Only an expert User could change this property.<br>\nIt defines the complete path of the gains coefficients file.<BR>";
	prop_def  = "";
	vect_data.clear();
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "ExpertPedestalFileName1";
	prop_desc = "Only an expert User could change this property.<br>\nIt defines the complete path of a pedestal image (first gain).<BR>";
	prop_def  = "";
	vect_data.clear();
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "ExpertPedestalFileName2";
	prop_desc = "Only an expert User could change this property.<br>\nIt defines the complete path of a pedestal image (second gain).<BR>";
	prop_def  = "";
	vect_data.clear();
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "ExpertPedestalFileName3";
	prop_desc = "Only an expert User could change this property.<br>\nIt defines the complete path of a pedestal image (third gain).<BR>";
	prop_def  = "";
	vect_data.clear();
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "ExpertPedestalNbFrames1";
	prop_desc = "Only an expert User could change this property.<br>\nIt defines the number of frames used to generate a pedestal image (first gain).<BR>";
	prop_def  = "";
	vect_data.clear();
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "ExpertPedestalNbFrames2";
	prop_desc = "Only an expert User could change this property.<br>\nIt defines the number of frames used to generate a pedestal image (second gain).<BR>";
	prop_def  = "";
	vect_data.clear();
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "ExpertPedestalNbFrames3";
	prop_desc = "Only an expert User could change this property.<br>\nIt defines the number of frames used to generate a pedestal image (third gain).<BR>";
	prop_def  = "";
	vect_data.clear();
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
}

//--------------------------------------------------------
/**
 *	Method      : SlsJungfrauClass::write_class_property()
 *	Description : Set class description fields as property in database
 */
//--------------------------------------------------------
void SlsJungfrauClass::write_class_property()
{
	//	First time, check if database used
	if (Tango::Util::_UseDb == false)
		return;

	Tango::DbData	data;
	string	classname = get_name();
	string	header;
	string::size_type	start, end;

	//	Put title
	Tango::DbDatum	title("ProjectTitle");
	string	str_title("Sls dectector TANGO specific device.");
	title << str_title;
	data.push_back(title);

	//	Put Description
	Tango::DbDatum	description("Description");
	vector<string>	str_desc;
	str_desc.push_back("Device for sls detectors from PSI. ");
	description << str_desc;
	data.push_back(description);

	//	put cvs or svn location
	string	filename("SlsJungfrau");
	filename += "Class.cpp";

	// check for cvs information
	string	src_path(CvsPath);
	start = src_path.find("/");
	if (start!=string::npos)
	{
		end   = src_path.find(filename);
		if (end>start)
		{
			string	strloc = src_path.substr(start, end-start);
			//	Check if specific repository
			start = strloc.find("/cvsroot/");
			if (start!=string::npos && start>0)
			{
				string	repository = strloc.substr(0, start);
				if (repository.find("/segfs/")!=string::npos)
					strloc = "ESRF:" + strloc.substr(start, strloc.length()-start);
			}
			Tango::DbDatum	cvs_loc("cvs_location");
			cvs_loc << strloc;
			data.push_back(cvs_loc);
		}
	}

	// check for svn information
	else
	{
		string	src_path(SvnPath);
		start = src_path.find("://");
		if (start!=string::npos)
		{
			end = src_path.find(filename);
			if (end>start)
			{
				header = "$HeadURL: ";
				start = header.length();
				string	strloc = src_path.substr(start, (end-start));
				
				Tango::DbDatum	svn_loc("svn_location");
				svn_loc << strloc;
				data.push_back(svn_loc);
			}
		}
	}

	//	Get CVS or SVN revision tag
	
	// CVS tag
	string	tagname(TagName);
	header = "$Name: ";
	start = header.length();
	string	endstr(" $");
	
	end   = tagname.find(endstr);
	if (end!=string::npos && end>start)
	{
		string	strtag = tagname.substr(start, end-start);
		Tango::DbDatum	cvs_tag("cvs_tag");
		cvs_tag << strtag;
		data.push_back(cvs_tag);
	}
	
	// SVN tag
	string	svnpath(SvnPath);
	header = "$HeadURL: ";
	start = header.length();
	
	end   = svnpath.find(endstr);
	if (end!=string::npos && end>start)
	{
		string	strloc = svnpath.substr(start, end-start);
		
		string tagstr ("/tags/");
		start = strloc.find(tagstr);
		if ( start!=string::npos )
		{
			start = start + tagstr.length();
			end   = strloc.find(filename);
			string	strtag = strloc.substr(start, end-start-1);
			
			Tango::DbDatum	svn_tag("svn_tag");
			svn_tag << strtag;
			data.push_back(svn_tag);
		}
	}

	//	Get URL location
	string	httpServ(HttpServer);
	if (httpServ.length()>0)
	{
		Tango::DbDatum	db_doc_url("doc_url");
		db_doc_url << httpServ;
		data.push_back(db_doc_url);
	}

	//  Put inheritance
	Tango::DbDatum	inher_datum("InheritedFrom");
	vector<string> inheritance;
	inheritance.push_back("Tango::Device_4Impl");
	inher_datum << inheritance;
	data.push_back(inher_datum);

	//	Call database and and values
	get_db_class()->put_property(data);
}

//===================================================================
//	Factory methods
//===================================================================

//--------------------------------------------------------
/**
 *	Method      : SlsJungfrauClass::device_factory()
 *	Description : Create the device object(s)
 *                and store them in the device list
 */
//--------------------------------------------------------
void SlsJungfrauClass::device_factory(const Tango::DevVarStringArray *devlist_ptr)
{
	/*----- PROTECTED REGION ID(SlsJungfrauClass::device_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	SlsJungfrauClass::device_factory_before

	//	Create devices and add it into the device list
	for (unsigned long i=0 ; i<devlist_ptr->length() ; i++)
	{
		cout4 << "Device name : " << (*devlist_ptr)[i].in() << endl;
		device_list.push_back(new SlsJungfrau(this, (*devlist_ptr)[i]));							 
	}

	//	Manage dynamic attributes if any
	//erase_dynamic_attributes(devlist_ptr, get_class_attr()->get_attr_list());

	//	Export devices to the outside world
	for (unsigned long i=1 ; i<=devlist_ptr->length() ; i++)
	{
		//	Add dynamic attributes if any
		SlsJungfrau *dev = static_cast<SlsJungfrau *>(device_list[device_list.size()-i]);
		//dev->add_dynamic_attributes();

		//	Check before if database used.
		if ((Tango::Util::_UseDb == true) && (Tango::Util::_FileDb == false))
			export_device(dev);
		else
			export_device(dev, dev->get_name().c_str());
	}

	/*----- PROTECTED REGION ID(SlsJungfrauClass::device_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	SlsJungfrauClass::device_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : SlsJungfrauClass::attribute_factory()
 *	Description : Create the attribute object(s)
 *                and store them in the attribute list
 */
//--------------------------------------------------------
void SlsJungfrauClass::attribute_factory(vector<Tango::Attr *> &att_list)
{
	/*----- PROTECTED REGION ID(SlsJungfrauClass::attribute_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	SlsJungfrauClass::attribute_factory_before
	//	Attribute : clockDivider
	clockDividerAttrib	*clockdivider = new clockDividerAttrib();
	Tango::UserDefaultAttrProp	clockdivider_prop;
	clockdivider_prop.set_description("Changes the readout clock.<br>\nAvailable clock Divider :<br>\nFULL_SPEED<br>\nHALF_SPEED<br>\nQUARTER_SPEED<br>\nSUPER_SLOW_SPEED<br>");
	//	label	not set for clockDivider
	//	unit	not set for clockDivider
	//	standard_unit	not set for clockDivider
	//	display_unit	not set for clockDivider
	//	format	not set for clockDivider
	//	max_value	not set for clockDivider
	//	min_value	not set for clockDivider
	//	max_alarm	not set for clockDivider
	//	min_alarm	not set for clockDivider
	//	max_warning	not set for clockDivider
	//	min_warning	not set for clockDivider
	//	delta_t	not set for clockDivider
	//	delta_val	not set for clockDivider
	
	clockdivider->set_default_properties(clockdivider_prop);
	//	Not Polled
	clockdivider->set_disp_level(Tango::OPERATOR);
	clockdivider->set_memorized();
	clockdivider->set_memorized_init(true);
	att_list.push_back(clockdivider);

	//	Attribute : configFileName
	configFileNameAttrib	*configfilename = new configFileNameAttrib();
	Tango::UserDefaultAttrProp	configfilename_prop;
	configfilename_prop.set_description("Shows the complete path of the configuration file.<br>");
	//	label	not set for configFileName
	//	unit	not set for configFileName
	//	standard_unit	not set for configFileName
	//	display_unit	not set for configFileName
	//	format	not set for configFileName
	//	max_value	not set for configFileName
	//	min_value	not set for configFileName
	//	max_alarm	not set for configFileName
	//	min_alarm	not set for configFileName
	//	max_warning	not set for configFileName
	//	min_warning	not set for configFileName
	//	delta_t	not set for configFileName
	//	delta_val	not set for configFileName
	
	configfilename->set_default_properties(configfilename_prop);
	//	Not Polled
	configfilename->set_disp_level(Tango::EXPERT);
	//	Not Memorized
	att_list.push_back(configfilename);

	//	Attribute : delayAfterTrigger
	delayAfterTriggerAttrib	*delayaftertrigger = new delayAfterTriggerAttrib();
	Tango::UserDefaultAttrProp	delayaftertrigger_prop;
	delayaftertrigger_prop.set_description("set/get delay after trigger in ms.");
	//	label	not set for delayAfterTrigger
	delayaftertrigger_prop.set_unit("ms");
	delayaftertrigger_prop.set_standard_unit("ms");
	delayaftertrigger_prop.set_display_unit("ms");
	delayaftertrigger_prop.set_format("%7.4f");
	//	max_value	not set for delayAfterTrigger
	//	min_value	not set for delayAfterTrigger
	//	max_alarm	not set for delayAfterTrigger
	//	min_alarm	not set for delayAfterTrigger
	//	max_warning	not set for delayAfterTrigger
	//	min_warning	not set for delayAfterTrigger
	//	delta_t	not set for delayAfterTrigger
	//	delta_val	not set for delayAfterTrigger
	
	delayaftertrigger->set_default_properties(delayaftertrigger_prop);
	//	Not Polled
	delayaftertrigger->set_disp_level(Tango::OPERATOR);
	delayaftertrigger->set_memorized();
	delayaftertrigger->set_memorized_init(true);
	att_list.push_back(delayaftertrigger);

	//	Attribute : detectorFirmwareVersion
	detectorFirmwareVersionAttrib	*detectorfirmwareversion = new detectorFirmwareVersionAttrib();
	Tango::UserDefaultAttrProp	detectorfirmwareversion_prop;
	detectorfirmwareversion_prop.set_description("Get detector firmware version.");
	detectorfirmwareversion_prop.set_label("detectorFirmwareVersion");
	//	unit	not set for detectorFirmwareVersion
	//	standard_unit	not set for detectorFirmwareVersion
	//	display_unit	not set for detectorFirmwareVersion
	//	format	not set for detectorFirmwareVersion
	//	max_value	not set for detectorFirmwareVersion
	//	min_value	not set for detectorFirmwareVersion
	//	max_alarm	not set for detectorFirmwareVersion
	//	min_alarm	not set for detectorFirmwareVersion
	//	max_warning	not set for detectorFirmwareVersion
	//	min_warning	not set for detectorFirmwareVersion
	//	delta_t	not set for detectorFirmwareVersion
	//	delta_val	not set for detectorFirmwareVersion
	
	detectorfirmwareversion->set_default_properties(detectorfirmwareversion_prop);
	//	Not Polled
	detectorfirmwareversion->set_disp_level(Tango::EXPERT);
	//	Not Memorized
	att_list.push_back(detectorfirmwareversion);

	//	Attribute : detectorSoftwareVersion
	detectorSoftwareVersionAttrib	*detectorsoftwareversion = new detectorSoftwareVersionAttrib();
	Tango::UserDefaultAttrProp	detectorsoftwareversion_prop;
	detectorsoftwareversion_prop.set_description("Get detector software version.");
	detectorsoftwareversion_prop.set_label("detectorSoftwareVersion");
	//	unit	not set for detectorSoftwareVersion
	//	standard_unit	not set for detectorSoftwareVersion
	//	display_unit	not set for detectorSoftwareVersion
	//	format	not set for detectorSoftwareVersion
	//	max_value	not set for detectorSoftwareVersion
	//	min_value	not set for detectorSoftwareVersion
	//	max_alarm	not set for detectorSoftwareVersion
	//	min_alarm	not set for detectorSoftwareVersion
	//	max_warning	not set for detectorSoftwareVersion
	//	min_warning	not set for detectorSoftwareVersion
	//	delta_t	not set for detectorSoftwareVersion
	//	delta_val	not set for detectorSoftwareVersion
	
	detectorsoftwareversion->set_default_properties(detectorsoftwareversion_prop);
	//	Not Polled
	detectorsoftwareversion->set_disp_level(Tango::EXPERT);
	//	Not Memorized
	att_list.push_back(detectorsoftwareversion);

	//	Attribute : gainMode
	gainModeAttrib	*gainmode = new gainModeAttrib();
	Tango::UserDefaultAttrProp	gainmode_prop;
	gainmode_prop.set_description("Changes the gain mode.<br>\nAvailable gain modes:<br>\nDYNAMIC -> dynamic gain settings<br>\nDYNAMICHG0 -> dynamic high gain 0<br>\nFIXGAIN1 -> fix gain 1<br>\nFIXGAIN2 -> fix gain 2<br>\nFORCESWITCHG1 -> force switch gain 1<br>\nFORCESWITCHG2 -> force switch gain 2<br>");
	//	label	not set for gainMode
	//	unit	not set for gainMode
	//	standard_unit	not set for gainMode
	//	display_unit	not set for gainMode
	//	format	not set for gainMode
	//	max_value	not set for gainMode
	//	min_value	not set for gainMode
	//	max_alarm	not set for gainMode
	//	min_alarm	not set for gainMode
	//	max_warning	not set for gainMode
	//	min_warning	not set for gainMode
	//	delta_t	not set for gainMode
	//	delta_val	not set for gainMode
	
	gainmode->set_default_properties(gainmode_prop);
	//	Not Polled
	gainmode->set_disp_level(Tango::OPERATOR);
	gainmode->set_memorized();
	gainmode->set_memorized_init(true);
	att_list.push_back(gainmode);

	//	Attribute : gainCoeffsFileName
	gainCoeffsFileNameAttrib	*gaincoeffsfilename = new gainCoeffsFileNameAttrib();
	Tango::UserDefaultAttrProp	gaincoeffsfilename_prop;
	gaincoeffsfilename_prop.set_description("Shows the complete path for the gains'coefficients file.<br>");
	//	label	not set for gainCoeffsFileName
	//	unit	not set for gainCoeffsFileName
	//	standard_unit	not set for gainCoeffsFileName
	//	display_unit	not set for gainCoeffsFileName
	//	format	not set for gainCoeffsFileName
	//	max_value	not set for gainCoeffsFileName
	//	min_value	not set for gainCoeffsFileName
	//	max_alarm	not set for gainCoeffsFileName
	//	min_alarm	not set for gainCoeffsFileName
	//	max_warning	not set for gainCoeffsFileName
	//	min_warning	not set for gainCoeffsFileName
	//	delta_t	not set for gainCoeffsFileName
	//	delta_val	not set for gainCoeffsFileName
	
	gaincoeffsfilename->set_default_properties(gaincoeffsfilename_prop);
	//	Not Polled
	gaincoeffsfilename->set_disp_level(Tango::EXPERT);
	//	Not Memorized
	att_list.push_back(gaincoeffsfilename);

	//	Attribute : pedestalFileName1
	pedestalFileName1Attrib	*pedestalfilename1 = new pedestalFileName1Attrib();
	Tango::UserDefaultAttrProp	pedestalfilename1_prop;
	pedestalfilename1_prop.set_description("Shows the complete path for the pedestal file of the first gain.<br>");
	//	label	not set for pedestalFileName1
	//	unit	not set for pedestalFileName1
	//	standard_unit	not set for pedestalFileName1
	//	display_unit	not set for pedestalFileName1
	//	format	not set for pedestalFileName1
	//	max_value	not set for pedestalFileName1
	//	min_value	not set for pedestalFileName1
	//	max_alarm	not set for pedestalFileName1
	//	min_alarm	not set for pedestalFileName1
	//	max_warning	not set for pedestalFileName1
	//	min_warning	not set for pedestalFileName1
	//	delta_t	not set for pedestalFileName1
	//	delta_val	not set for pedestalFileName1
	
	pedestalfilename1->set_default_properties(pedestalfilename1_prop);
	//	Not Polled
	pedestalfilename1->set_disp_level(Tango::EXPERT);
	//	Not Memorized
	att_list.push_back(pedestalfilename1);

	//	Attribute : pedestalFileName2
	pedestalFileName2Attrib	*pedestalfilename2 = new pedestalFileName2Attrib();
	Tango::UserDefaultAttrProp	pedestalfilename2_prop;
	pedestalfilename2_prop.set_description("Shows the complete path for the pedestal file of the second gain.<br>");
	//	label	not set for pedestalFileName2
	//	unit	not set for pedestalFileName2
	//	standard_unit	not set for pedestalFileName2
	//	display_unit	not set for pedestalFileName2
	//	format	not set for pedestalFileName2
	//	max_value	not set for pedestalFileName2
	//	min_value	not set for pedestalFileName2
	//	max_alarm	not set for pedestalFileName2
	//	min_alarm	not set for pedestalFileName2
	//	max_warning	not set for pedestalFileName2
	//	min_warning	not set for pedestalFileName2
	//	delta_t	not set for pedestalFileName2
	//	delta_val	not set for pedestalFileName2
	
	pedestalfilename2->set_default_properties(pedestalfilename2_prop);
	//	Not Polled
	pedestalfilename2->set_disp_level(Tango::EXPERT);
	//	Not Memorized
	att_list.push_back(pedestalfilename2);

	//	Attribute : pedestalFileName3
	pedestalFileName3Attrib	*pedestalfilename3 = new pedestalFileName3Attrib();
	Tango::UserDefaultAttrProp	pedestalfilename3_prop;
	pedestalfilename3_prop.set_description("Shows the complete path for the pedestal file of the third gain.<br>");
	//	label	not set for pedestalFileName3
	//	unit	not set for pedestalFileName3
	//	standard_unit	not set for pedestalFileName3
	//	display_unit	not set for pedestalFileName3
	//	format	not set for pedestalFileName3
	//	max_value	not set for pedestalFileName3
	//	min_value	not set for pedestalFileName3
	//	max_alarm	not set for pedestalFileName3
	//	min_alarm	not set for pedestalFileName3
	//	max_warning	not set for pedestalFileName3
	//	min_warning	not set for pedestalFileName3
	//	delta_t	not set for pedestalFileName3
	//	delta_val	not set for pedestalFileName3
	
	pedestalfilename3->set_default_properties(pedestalfilename3_prop);
	//	Not Polled
	pedestalfilename3->set_disp_level(Tango::EXPERT);
	//	Not Memorized
	att_list.push_back(pedestalfilename3);

	//	Attribute : gainCoeffsState
	gainCoeffsStateAttrib	*gaincoeffsstate = new gainCoeffsStateAttrib();
	Tango::UserDefaultAttrProp	gaincoeffsstate_prop;
	gaincoeffsstate_prop.set_description("Shows the status of the gains coefficients state<br>\nIt can be:<br>\n- NONE (not loaded)<br>\n- LOADED<br>");
	//	label	not set for gainCoeffsState
	//	unit	not set for gainCoeffsState
	//	standard_unit	not set for gainCoeffsState
	//	display_unit	not set for gainCoeffsState
	//	format	not set for gainCoeffsState
	//	max_value	not set for gainCoeffsState
	//	min_value	not set for gainCoeffsState
	//	max_alarm	not set for gainCoeffsState
	//	min_alarm	not set for gainCoeffsState
	//	max_warning	not set for gainCoeffsState
	//	min_warning	not set for gainCoeffsState
	//	delta_t	not set for gainCoeffsState
	//	delta_val	not set for gainCoeffsState
	
	gaincoeffsstate->set_default_properties(gaincoeffsstate_prop);
	//	Not Polled
	gaincoeffsstate->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(gaincoeffsstate);

	//	Attribute : calibrationState
	calibrationStateAttrib	*calibrationstate = new calibrationStateAttrib();
	Tango::UserDefaultAttrProp	calibrationstate_prop;
	calibrationstate_prop.set_description("Shows the status of the calibration state<br>\nIt can be:<br>\n- NONE (no calibration loaded or generated)<br>\n- LOADED (a previous saved calibration was loaded)<br>\n- RUNNING_0_3 (a calibration is running and at the moment no pedestal was generated)<br>\n- RUNNING_1_3 (a calibration is running and the first pedestal was generated)<br>\n- RUNNING_2_3 (a calibration is running and two pedestals were generated)<br>\n- GENERATED (a new calibration was done)<br>");
	//	label	not set for calibrationState
	//	unit	not set for calibrationState
	//	standard_unit	not set for calibrationState
	//	display_unit	not set for calibrationState
	//	format	not set for calibrationState
	//	max_value	not set for calibrationState
	//	min_value	not set for calibrationState
	//	max_alarm	not set for calibrationState
	//	min_alarm	not set for calibrationState
	//	max_warning	not set for calibrationState
	//	min_warning	not set for calibrationState
	//	delta_t	not set for calibrationState
	//	delta_val	not set for calibrationState
	
	calibrationstate->set_default_properties(calibrationstate_prop);
	//	Not Polled
	calibrationstate->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(calibrationstate);

	//	Attribute : gainCoeffs1
	gainCoeffs1Attrib	*gaincoeffs1 = new gainCoeffs1Attrib();
	Tango::UserDefaultAttrProp	gaincoeffs1_prop;
	gaincoeffs1_prop.set_description("Shows the coefficients for the first gain.<br>");
	//	label	not set for gainCoeffs1
	//	unit	not set for gainCoeffs1
	//	standard_unit	not set for gainCoeffs1
	//	display_unit	not set for gainCoeffs1
	//	format	not set for gainCoeffs1
	//	max_value	not set for gainCoeffs1
	//	min_value	not set for gainCoeffs1
	//	max_alarm	not set for gainCoeffs1
	//	min_alarm	not set for gainCoeffs1
	//	max_warning	not set for gainCoeffs1
	//	min_warning	not set for gainCoeffs1
	//	delta_t	not set for gainCoeffs1
	//	delta_val	not set for gainCoeffs1
	
	gaincoeffs1->set_default_properties(gaincoeffs1_prop);
	//	Not Polled
	gaincoeffs1->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(gaincoeffs1);

	//	Attribute : gainCoeffs2
	gainCoeffs2Attrib	*gaincoeffs2 = new gainCoeffs2Attrib();
	Tango::UserDefaultAttrProp	gaincoeffs2_prop;
	gaincoeffs2_prop.set_description("Shows the coefficients for the second gain.<br>");
	//	label	not set for gainCoeffs2
	//	unit	not set for gainCoeffs2
	//	standard_unit	not set for gainCoeffs2
	//	display_unit	not set for gainCoeffs2
	//	format	not set for gainCoeffs2
	//	max_value	not set for gainCoeffs2
	//	min_value	not set for gainCoeffs2
	//	max_alarm	not set for gainCoeffs2
	//	min_alarm	not set for gainCoeffs2
	//	max_warning	not set for gainCoeffs2
	//	min_warning	not set for gainCoeffs2
	//	delta_t	not set for gainCoeffs2
	//	delta_val	not set for gainCoeffs2
	
	gaincoeffs2->set_default_properties(gaincoeffs2_prop);
	//	Not Polled
	gaincoeffs2->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(gaincoeffs2);

	//	Attribute : gainCoeffs3
	gainCoeffs3Attrib	*gaincoeffs3 = new gainCoeffs3Attrib();
	Tango::UserDefaultAttrProp	gaincoeffs3_prop;
	gaincoeffs3_prop.set_description("Shows the coefficients for the third gain.<br>");
	//	label	not set for gainCoeffs3
	//	unit	not set for gainCoeffs3
	//	standard_unit	not set for gainCoeffs3
	//	display_unit	not set for gainCoeffs3
	//	format	not set for gainCoeffs3
	//	max_value	not set for gainCoeffs3
	//	min_value	not set for gainCoeffs3
	//	max_alarm	not set for gainCoeffs3
	//	min_alarm	not set for gainCoeffs3
	//	max_warning	not set for gainCoeffs3
	//	min_warning	not set for gainCoeffs3
	//	delta_t	not set for gainCoeffs3
	//	delta_val	not set for gainCoeffs3
	
	gaincoeffs3->set_default_properties(gaincoeffs3_prop);
	//	Not Polled
	gaincoeffs3->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(gaincoeffs3);

	//	Attribute : pedestal1
	pedestal1Attrib	*pedestal1 = new pedestal1Attrib();
	Tango::UserDefaultAttrProp	pedestal1_prop;
	pedestal1_prop.set_description("Shows the pedestal image for the first gain.<br>");
	//	label	not set for pedestal1
	//	unit	not set for pedestal1
	//	standard_unit	not set for pedestal1
	//	display_unit	not set for pedestal1
	//	format	not set for pedestal1
	//	max_value	not set for pedestal1
	//	min_value	not set for pedestal1
	//	max_alarm	not set for pedestal1
	//	min_alarm	not set for pedestal1
	//	max_warning	not set for pedestal1
	//	min_warning	not set for pedestal1
	//	delta_t	not set for pedestal1
	//	delta_val	not set for pedestal1
	
	pedestal1->set_default_properties(pedestal1_prop);
	//	Not Polled
	pedestal1->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(pedestal1);

	//	Attribute : pedestal2
	pedestal2Attrib	*pedestal2 = new pedestal2Attrib();
	Tango::UserDefaultAttrProp	pedestal2_prop;
	pedestal2_prop.set_description("Shows the pedestal image for the second gain.<br>");
	//	label	not set for pedestal2
	//	unit	not set for pedestal2
	//	standard_unit	not set for pedestal2
	//	display_unit	not set for pedestal2
	//	format	not set for pedestal2
	//	max_value	not set for pedestal2
	//	min_value	not set for pedestal2
	//	max_alarm	not set for pedestal2
	//	min_alarm	not set for pedestal2
	//	max_warning	not set for pedestal2
	//	min_warning	not set for pedestal2
	//	delta_t	not set for pedestal2
	//	delta_val	not set for pedestal2
	
	pedestal2->set_default_properties(pedestal2_prop);
	//	Not Polled
	pedestal2->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(pedestal2);

	//	Attribute : pedestal3
	pedestal3Attrib	*pedestal3 = new pedestal3Attrib();
	Tango::UserDefaultAttrProp	pedestal3_prop;
	pedestal3_prop.set_description("Shows the pedestal image for the third gain.<br>");
	//	label	not set for pedestal3
	//	unit	not set for pedestal3
	//	standard_unit	not set for pedestal3
	//	display_unit	not set for pedestal3
	//	format	not set for pedestal3
	//	max_value	not set for pedestal3
	//	min_value	not set for pedestal3
	//	max_alarm	not set for pedestal3
	//	min_alarm	not set for pedestal3
	//	max_warning	not set for pedestal3
	//	min_warning	not set for pedestal3
	//	delta_t	not set for pedestal3
	//	delta_val	not set for pedestal3
	
	pedestal3->set_default_properties(pedestal3_prop);
	//	Not Polled
	pedestal3->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(pedestal3);

	//	Create a list of static attributes
	create_static_attribute_list(get_class_attr()->get_attr_list());
	/*----- PROTECTED REGION ID(SlsJungfrauClass::attribute_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	SlsJungfrauClass::attribute_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : SlsJungfrauClass::command_factory()
 *	Description : Create the command object(s)
 *                and store them in the command list
 */
//--------------------------------------------------------
void SlsJungfrauClass::command_factory()
{
	/*----- PROTECTED REGION ID(SlsJungfrauClass::command_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	SlsJungfrauClass::command_factory_before


	//	Command SetCmd
	SetCmdClass	*pSetCmdCmd =
		new SetCmdClass("SetCmd",
			Tango::DEV_STRING, Tango::DEV_STRING,
			"SlsDetector command",
			"SlsDetector response",
			Tango::EXPERT);
	command_list.push_back(pSetCmdCmd);

	//	Command GetCmd
	GetCmdClass	*pGetCmdCmd =
		new GetCmdClass("GetCmd",
			Tango::DEV_STRING, Tango::DEV_STRING,
			"SlsDetector command",
			"SlsDetector response",
			Tango::EXPERT);
	command_list.push_back(pGetCmdCmd);

	//	Command ResetCamera
	ResetCameraClass	*pResetCameraCmd =
		new ResetCameraClass("ResetCamera",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::EXPERT);
	command_list.push_back(pResetCameraCmd);

	//	Command Calibrate
	CalibrateClass	*pCalibrateCmd =
		new CalibrateClass("Calibrate",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pCalibrateCmd);

	/*----- PROTECTED REGION ID(SlsJungfrauClass::command_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	SlsJungfrauClass::command_factory_after
}

//===================================================================
//	Dynamic attributes related methods
//===================================================================

//--------------------------------------------------------
/**
 * method : 		SlsJungfrauClass::create_static_attribute_list
 * description : 	Create the a list of static attributes
 *
 * @param	att_list	the ceated attribute list 
 */
//--------------------------------------------------------
void SlsJungfrauClass::create_static_attribute_list(vector<Tango::Attr *> &att_list)
{
	for (unsigned long i=0 ; i<att_list.size() ; i++)
	{
		string att_name(att_list[i]->get_name());
		transform(att_name.begin(), att_name.end(), att_name.begin(), ::tolower);
		defaultAttList.push_back(att_name);
	}

	cout2 << defaultAttList.size() << " attributes in default list" << endl;

	/*----- PROTECTED REGION ID(SlsJungfrauClass::create_static_att_list) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SlsJungfrauClass::create_static_att_list
}


//--------------------------------------------------------
/**
 * method : 		SlsJungfrauClass::erase_dynamic_attributes
 * description : 	delete the dynamic attributes if any.
 *
 * @param	devlist_ptr	the device list pointer
 * @param	list of all attributes
 */
//--------------------------------------------------------
void SlsJungfrauClass::erase_dynamic_attributes(const Tango::DevVarStringArray *devlist_ptr, vector<Tango::Attr *> &att_list)
{
	Tango::Util *tg = Tango::Util::instance();

	for (unsigned long i=0 ; i<devlist_ptr->length() ; i++)
	{	
		Tango::DeviceImpl *dev_impl = tg->get_device_by_name(((string)(*devlist_ptr)[i]).c_str());
		SlsJungfrau *dev = static_cast<SlsJungfrau *> (dev_impl);
		
		vector<Tango::Attribute *> &dev_att_list = dev->get_device_attr()->get_attribute_list();
		vector<Tango::Attribute *>::iterator ite_att;
		for (ite_att=dev_att_list.begin() ; ite_att != dev_att_list.end() ; ++ite_att)
		{
			string att_name((*ite_att)->get_name_lower());
			if ((att_name == "state") || (att_name == "status"))
				continue;
			vector<string>::iterator ite_str = find(defaultAttList.begin(), defaultAttList.end(), att_name);
			if (ite_str == defaultAttList.end())
			{
				cout2 << att_name << " is a UNWANTED dynamic attribute for device " << (*devlist_ptr)[i] << endl;
				Tango::Attribute &att = dev->get_device_attr()->get_attr_by_name(att_name.c_str());
				dev->remove_attribute(att_list[att.get_attr_idx()], true, false);
				--ite_att;
			}
		}
	}
	/*----- PROTECTED REGION ID(SlsJungfrauClass::erase_dynamic_attributes) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SlsJungfrauClass::erase_dynamic_attributes
}

//--------------------------------------------------------
/**
 *	Method      : SlsJungfrauClass::get_attr_by_name()
 *	Description : returns Tango::Attr * object found by name
 */
//--------------------------------------------------------
Tango::Attr *SlsJungfrauClass::get_attr_object_by_name(vector<Tango::Attr *> &att_list, string attname)
{
	vector<Tango::Attr *>::iterator it;
	for (it=att_list.begin() ; it<att_list.end() ; it++)
		if ((*it)->get_name()==attname)
			return (*it);
	//	Attr does not exist
	return NULL;
}


/*----- PROTECTED REGION ID(SlsJungfrauClass::Additional Methods) ENABLED START -----*/

/*----- PROTECTED REGION END -----*/	//	SlsJungfrauClass::Additional Methods
} //	namespace
