/*----- PROTECTED REGION ID(DhyanaClass.cpp) ENABLED START -----*/
static const char *RcsId      = "$Id:  $";
static const char *TagName    = "$Name:  $";
static const char *CvsPath    = "$Source:  $";
static const char *SvnPath    = "$HeadURL:  $";
static const char *HttpServer = "http://www.esrf.eu/computing/cs/tango/tango_doc/ds_doc/";
//=============================================================================
//
// file :        DhyanaClass.cpp
//
// description : C++ source for the DhyanaClass.
//               A singleton class derived from DeviceClass.
//               It implements the command and attribute list
//               and all properties and methods required
//               by the Dhyana once per process.
//
// project :     Device specific for Dhyana detector
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#ifdef WIN32
#include "tango.h"
#endif
#include <Dhyana.h>
#include <DhyanaClass.h>

#ifndef WIN32
#include "tango.h"
#endif

/*----- PROTECTED REGION END -----*/	//	DhyanaClass.cpp

//-------------------------------------------------------------------
/**
 *	Create DhyanaClass singleton and
 *	return it in a C function for Python usage
 */
//-------------------------------------------------------------------
extern "C" {
#ifdef _TG_WINDOWS_

__declspec(dllexport)

#endif

	Tango::DeviceClass *_create_Dhyana_class(const char *name) {
		return Dhyana_ns::DhyanaClass::init(name);
	}
}

namespace Dhyana_ns
{
//===================================================================
//	Initialize pointer for singleton pattern
//===================================================================
DhyanaClass *DhyanaClass::_instance = NULL;

//--------------------------------------------------------
/**
 * method : 		DhyanaClass::DhyanaClass(string &s)
 * description : 	constructor for the DhyanaClass
 *
 * @param s	The class name
 */
//--------------------------------------------------------
DhyanaClass::DhyanaClass(string &s):Tango::DeviceClass(s)
{
	cout2 << "Entering DhyanaClass constructor" << endl;
	set_default_property();
	write_class_property();

	/*----- PROTECTED REGION ID(DhyanaClass::constructor) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	DhyanaClass::constructor

	cout2 << "Leaving DhyanaClass constructor" << endl;
}

//--------------------------------------------------------
/**
 * method : 		DhyanaClass::~DhyanaClass()
 * description : 	destructor for the DhyanaClass
 */
//--------------------------------------------------------
DhyanaClass::~DhyanaClass()
{
	/*----- PROTECTED REGION ID(DhyanaClass::destructor) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	DhyanaClass::destructor

	_instance = NULL;
}


//--------------------------------------------------------
/**
 * method : 		DhyanaClass::init
 * description : 	Create the object if not already done.
 *                  Otherwise, just return a pointer to the object
 *
 * @param	name	The class name
 */
//--------------------------------------------------------
DhyanaClass *DhyanaClass::init(const char *name)
{
	if (_instance == NULL)
	{
		try
		{
			string s(name);
			_instance = new DhyanaClass(s);
		}
		catch (bad_alloc &)
		{
			throw;
		}
	}
	return _instance;
}

//--------------------------------------------------------
/**
 * method : 		DhyanaClass::instance
 * description : 	Check if object already created,
 *                  and return a pointer to the object
 */
//--------------------------------------------------------
DhyanaClass *DhyanaClass::instance()
{
	if (_instance == NULL)
	{
		cerr << "Class is not initialised !!" << endl;
		exit(-1);
	}
	return _instance;
}



//===================================================================
//	Command execution method calls
//===================================================================
//--------------------------------------------------------
/**
 * method : 		GetAllParametersClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *GetAllParametersClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "GetAllParametersClass::execute(): arrived" << endl;
	return insert((static_cast<Dhyana *>(device))->get_all_parameters());
}

//--------------------------------------------------------
/**
 * method : 		GetParameterClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *GetParameterClass::execute(Tango::DeviceImpl *device, const CORBA::Any &in_any)
{
	cout2 << "GetParameterClass::execute(): arrived" << endl;
	Tango::DevString argin;
	extract(in_any, argin);
	return insert((static_cast<Dhyana *>(device))->get_parameter(argin));
}

//--------------------------------------------------------
/**
 * method : 		SetParameterClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *SetParameterClass::execute(Tango::DeviceImpl *device, const CORBA::Any &in_any)
{
	cout2 << "SetParameterClass::execute(): arrived" << endl;
	const Tango::DevVarStringArray *argin;
	extract(in_any, argin);
	((static_cast<Dhyana *>(device))->set_parameter(argin));
	return new CORBA::Any();
}


//===================================================================
//	Properties management
//===================================================================
//--------------------------------------------------------
/**
 *	Method      : DhyanaClass::get_class_property()
 *	Description : Get the class property for specified name.
 */
//--------------------------------------------------------
Tango::DbDatum DhyanaClass::get_class_property(string &prop_name)
{
	for (unsigned int i=0 ; i<cl_prop.size() ; i++)
		if (cl_prop[i].name == prop_name)
			return cl_prop[i];
	//	if not found, returns  an empty DbDatum
	return Tango::DbDatum(prop_name);
}

//--------------------------------------------------------
/**
 *	Method      : DhyanaClass::get_default_device_property()
 *	Description : Return the default value for device property.
 */
//--------------------------------------------------------
Tango::DbDatum DhyanaClass::get_default_device_property(string &prop_name)
{
	for (unsigned int i=0 ; i<dev_def_prop.size() ; i++)
		if (dev_def_prop[i].name == prop_name)
			return dev_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}

//--------------------------------------------------------
/**
 *	Method      : DhyanaClass::get_default_class_property()
 *	Description : Return the default value for class property.
 */
//--------------------------------------------------------
Tango::DbDatum DhyanaClass::get_default_class_property(string &prop_name)
{
	for (unsigned int i=0 ; i<cl_def_prop.size() ; i++)
		if (cl_def_prop[i].name == prop_name)
			return cl_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}


//--------------------------------------------------------
/**
 *	Method      : DhyanaClass::set_default_property()
 *	Description : Set default property (class and device) for wizard.
 *                For each property, add to wizard property name and description.
 *                If default value has been set, add it to wizard property and
 *                store it in a DbDatum.
 */
//--------------------------------------------------------
void DhyanaClass::set_default_property()
{
	string	prop_name;
	string	prop_desc;
	string	prop_def;
	vector<string>	vect_data;

	//	Set Default Class Properties

	//	Set Default device Properties
	prop_name = "__ExpertTimerPeriod";
	prop_desc = "Timer period in ms.<cr>\nuseful only for Internal Trigger";
	prop_def  = "1";
	vect_data.clear();
	vect_data.push_back("1");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "TemperatureTargetAtInit";
	prop_desc = "TemperatureTarget at init (default is 15)";
	prop_def  = "15";
	vect_data.clear();
	vect_data.push_back("15");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
}

//--------------------------------------------------------
/**
 *	Method      : DhyanaClass::write_class_property()
 *	Description : Set class description fields as property in database
 */
//--------------------------------------------------------
void DhyanaClass::write_class_property()
{
	//	First time, check if database used
	if (Tango::Util::_UseDb == false)
		return;

	Tango::DbData	data;
	string	classname = get_name();
	string	header;
	string::size_type	start, end;

	//	Put title
	Tango::DbDatum	title("ProjectTitle");
	string	str_title("Device specific for Dhyana detector");
	title << str_title;
	data.push_back(title);

	//	Put Description
	Tango::DbDatum	description("Description");
	vector<string>	str_desc;
	str_desc.push_back("Interface the camera Dhyana using  the TUCAM Library");
	description << str_desc;
	data.push_back(description);

	//  Put inheritance
	Tango::DbDatum	inher_datum("InheritedFrom");
	vector<string> inheritance;
	inheritance.push_back("TANGO_BASE_CLASS");
	inher_datum << inheritance;
	data.push_back(inher_datum);

	//	Call database and and values
	get_db_class()->put_property(data);
}

//===================================================================
//	Factory methods
//===================================================================

//--------------------------------------------------------
/**
 *	Method      : DhyanaClass::device_factory()
 *	Description : Create the device object(s)
 *                and store them in the device list
 */
//--------------------------------------------------------
void DhyanaClass::device_factory(const Tango::DevVarStringArray *devlist_ptr)
{
	/*----- PROTECTED REGION ID(DhyanaClass::device_factory_before) ENABLED START -----*/
	
	//	Add your own code

	//	Create devices and add it into the device list
	for (unsigned long i=0 ; i<devlist_ptr->length() ; i++)
	{
		cout4 << "Device name : " << (*devlist_ptr)[i].in() << endl;
		device_list.push_back(new Dhyana(this, (*devlist_ptr)[i]));
	}

	//	Manage dynamic attributes if any
	//erase_dynamic_attributes(devlist_ptr, get_class_attr()->get_attr_list());

	//	Export devices to the outside world
	for (unsigned long i=1 ; i<=devlist_ptr->length() ; i++)
	{
		//	Add dynamic attributes if any
		Dhyana *dev = static_cast<Dhyana *>(device_list[device_list.size()-i]);
		dev->add_dynamic_attributes();

		//	Check before if database used.
		if ((Tango::Util::_UseDb == true) && (Tango::Util::_FileDb == false))
			export_device(dev);
		else
			export_device(dev, dev->get_name().c_str());
	}

	return;
	
	/*----- PROTECTED REGION END -----*/	//	DhyanaClass::device_factory_before

	//	Create devices and add it into the device list
	for (unsigned long i=0 ; i<devlist_ptr->length() ; i++)
	{
		cout4 << "Device name : " << (*devlist_ptr)[i].in() << endl;
		device_list.push_back(new Dhyana(this, (*devlist_ptr)[i]));
	}

	//	Manage dynamic attributes if any
	erase_dynamic_attributes(devlist_ptr, get_class_attr()->get_attr_list());

	//	Export devices to the outside world
	for (unsigned long i=1 ; i<=devlist_ptr->length() ; i++)
	{
		//	Add dynamic attributes if any
		Dhyana *dev = static_cast<Dhyana *>(device_list[device_list.size()-i]);
		dev->add_dynamic_attributes();

		//	Check before if database used.
		if ((Tango::Util::_UseDb == true) && (Tango::Util::_FileDb == false))
			export_device(dev);
		else
			export_device(dev, dev->get_name().c_str());
	}

	/*----- PROTECTED REGION ID(DhyanaClass::device_factory_after) ENABLED START -----*/

	

	/*----- PROTECTED REGION END -----*/	//	DhyanaClass::device_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : DhyanaClass::attribute_factory()
 *	Description : Create the attribute object(s)
 *                and store them in the attribute list
 */
//--------------------------------------------------------
void DhyanaClass::attribute_factory(vector<Tango::Attr *> &att_list)
{
	/*----- PROTECTED REGION ID(DhyanaClass::attribute_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	DhyanaClass::attribute_factory_before

	//	Create a list of static attributes
	create_static_attribute_list(get_class_attr()->get_attr_list());
	/*----- PROTECTED REGION ID(DhyanaClass::attribute_factory_after) ENABLED START -----*/
	
	/*channel1Attrib *triggerout1 = new channel1Attrib();
	Tango::UserDefaultAttrProp triggerout1_prop;
	vector<string> triggerout_labels = {"ExposureStart", "Readout", "Global"};
	triggerout1_prop.set_enum_labels(triggerout_labels);
	triggerout1->set_default_properties(triggerout1_prop);
	att_list.push_back(triggerout1);

	channel2Attrib *triggerout2 = new channel2Attrib();
	Tango::UserDefaultAttrProp triggerout2_prop;
	triggerout2_prop.set_enum_labels(triggerout_labels);
	triggerout2->set_default_properties(triggerout2_prop);
	att_list.push_back(triggerout2);

	channel3Attrib *triggerout3 = new channel3Attrib();
	Tango::UserDefaultAttrProp triggerout3_prop;
	triggerout3_prop.set_enum_labels(triggerout_labels);
	triggerout3->set_default_properties(triggerout3_prop);
	att_list.push_back(triggerout3);
	

	edge1Attrib *edgeout1 = new edge1Attrib();
	Tango::UserDefaultAttrProp edgeout1_prop;
	vector<string> edge_labels = {"Raising", "Failing"};
	edgeout1_prop.set_enum_labels(edge_labels);
	edgeout1->set_default_properties(edgeout1_prop);
	att_list.push_back(edgeout1);

	edge2Attrib *edgeout2 = new edge2Attrib();
	Tango::UserDefaultAttrProp edgeout2_prop;
	edgeout2_prop.set_enum_labels(edge_labels);
	edgeout2->set_default_properties(edgeout2_prop);
	att_list.push_back(edgeout2);

	edge3Attrib *edgeout3 = new edge3Attrib();
	Tango::UserDefaultAttrProp edgeout3_prop;
	edgeout3_prop.set_enum_labels(edge_labels);
	edgeout3->set_default_properties(edgeout3_prop);
	att_list.push_back(edgeout3);*/
	/*----- PROTECTED REGION END -----*/	//	DhyanaClass::attribute_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : DhyanaClass::pipe_factory()
 *	Description : Create the pipe object(s)
 *                and store them in the pipe list
 */
//--------------------------------------------------------
void DhyanaClass::pipe_factory()
{
	/*----- PROTECTED REGION ID(DhyanaClass::pipe_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	DhyanaClass::pipe_factory_before
	/*----- PROTECTED REGION ID(DhyanaClass::pipe_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	DhyanaClass::pipe_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : DhyanaClass::command_factory()
 *	Description : Create the command object(s)
 *                and store them in the command list
 */
//--------------------------------------------------------
void DhyanaClass::command_factory()
{
	/*----- PROTECTED REGION ID(DhyanaClass::command_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	DhyanaClass::command_factory_before


	//	Command GetAllParameters
	GetAllParametersClass	*pGetAllParametersCmd =
		new GetAllParametersClass("GetAllParameters",
			Tango::DEV_VOID, Tango::DEV_STRING,
			"",
			"",
			Tango::EXPERT);
	command_list.push_back(pGetAllParametersCmd);

	//	Command GetParameter
	GetParameterClass	*pGetParameterCmd =
		new GetParameterClass("GetParameter",
			Tango::DEV_STRING, Tango::DEV_STRING,
			"",
			"",
			Tango::EXPERT);
	command_list.push_back(pGetParameterCmd);

	//	Command SetParameter
	SetParameterClass	*pSetParameterCmd =
		new SetParameterClass("SetParameter",
			Tango::DEVVAR_STRINGARRAY, Tango::DEV_VOID,
			"",
			"",
			Tango::EXPERT);
	command_list.push_back(pSetParameterCmd);

	/*----- PROTECTED REGION ID(DhyanaClass::command_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	DhyanaClass::command_factory_after
}

//===================================================================
//	Dynamic attributes related methods
//===================================================================

//--------------------------------------------------------
/**
 * method : 		DhyanaClass::create_static_attribute_list
 * description : 	Create the a list of static attributes
 *
 * @param	att_list	the ceated attribute list
 */
//--------------------------------------------------------
void DhyanaClass::create_static_attribute_list(vector<Tango::Attr *> &att_list)
{
	for (unsigned long i=0 ; i<att_list.size() ; i++)
	{
		string att_name(att_list[i]->get_name());
		transform(att_name.begin(), att_name.end(), att_name.begin(), ::tolower);
		defaultAttList.push_back(att_name);
	}

	cout2 << defaultAttList.size() << " attributes in default list" << endl;

	/*----- PROTECTED REGION ID(DhyanaClass::create_static_att_list) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	DhyanaClass::create_static_att_list
}


//--------------------------------------------------------
/**
 * method : 		DhyanaClass::erase_dynamic_attributes
 * description : 	delete the dynamic attributes if any.
 *
 * @param	devlist_ptr	the device list pointer
 * @param	list of all attributes
 */
//--------------------------------------------------------
void DhyanaClass::erase_dynamic_attributes(const Tango::DevVarStringArray *devlist_ptr, vector<Tango::Attr *> &att_list)
{
	Tango::Util *tg = Tango::Util::instance();

	for (unsigned long i=0 ; i<devlist_ptr->length() ; i++)
	{
		Tango::DeviceImpl *dev_impl = tg->get_device_by_name(((string)(*devlist_ptr)[i]).c_str());
		Dhyana *dev = static_cast<Dhyana *> (dev_impl);

		vector<Tango::Attribute *> &dev_att_list = dev->get_device_attr()->get_attribute_list();
		vector<Tango::Attribute *>::iterator ite_att;
		for (ite_att=dev_att_list.begin() ; ite_att != dev_att_list.end() ; ++ite_att)
		{
			string att_name((*ite_att)->get_name_lower());
			if ((att_name == "state") || (att_name == "status"))
				continue;
			vector<string>::iterator ite_str = find(defaultAttList.begin(), defaultAttList.end(), att_name);
			if (ite_str == defaultAttList.end())
			{
				cout2 << att_name << " is a UNWANTED dynamic attribute for device " << (*devlist_ptr)[i] << endl;
				Tango::Attribute &att = dev->get_device_attr()->get_attr_by_name(att_name.c_str());
				dev->remove_attribute(att_list[att.get_attr_idx()], true, false);
				--ite_att;
			}
		}
	}
	/*----- PROTECTED REGION ID(DhyanaClass::erase_dynamic_attributes) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	DhyanaClass::erase_dynamic_attributes
}

//--------------------------------------------------------
/**
 *	Method      : DhyanaClass::get_attr_object_by_name()
 *	Description : returns Tango::Attr * object found by name
 */
//--------------------------------------------------------
Tango::Attr *DhyanaClass::get_attr_object_by_name(vector<Tango::Attr *> &att_list, string attname)
{
	vector<Tango::Attr *>::iterator it;
	for (it=att_list.begin() ; it<att_list.end() ; ++it)
		if ((*it)->get_name()==attname)
			return (*it);
	//	Attr does not exist
	return NULL;
}


/*----- PROTECTED REGION ID(DhyanaClass::Additional Methods) ENABLED START -----*/

/*----- PROTECTED REGION END -----*/	//	DhyanaClass::Additional Methods
} //	namespace
