/*----- PROTECTED REGION ID(Mask.h) ENABLED START -----*/

//=============================================================================
//
// file :        Mask.h
//
// description : Include file for the Mask class
//
// project :     Lima
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#ifndef Mask_H
#define Mask_H

#include "Factory.h"
#include <tango.h>
#include <yat4tango/DynamicInterfaceManager.h>
#include <yat4tango/PropertyHelper.h>
#include <yat4tango/InnerAppender.h>
#include <yat/threading/Mutex.h>
#include <yat/utils/XString.h>

#include "lima/HwInterface.h"
#include "lima/CtControl.h"
#include "lima/CtAcquisition.h"
#include "lima/CtImage.h"
#include "lima/CtVideo.h"
#include "lima/SoftOpId.h"
#include "lima/SoftOpExternalMgr.h"
#include "processlib/Data.h"
#include "processlib/TaskMgr.h"
#include <map>


#define MAX_ATTRIBUTE_STRING_LENGTH     256
#define MASK_CURRENT_VERSION                 "1.0.0"

/*----- PROTECTED REGION END -----*/	//	Mask.h

/**
 *  Mask class description:
 *    
 */

namespace Mask_ns
{
/*----- PROTECTED REGION ID(Mask::Additional Class Declarations) ENABLED START -----*/


/**
 * Class Description:
 *
 */

/*
 *	Device States Description:
*  Tango::INIT :
*  Tango::STANDBY :
*  Tango::FAULT :
*  Tango::RUNNING :
 */

/*----- PROTECTED REGION END -----*/	//	Mask::Additional Class Declarations

class Mask : public TANGO_BASE_CLASS
{

/*----- PROTECTED REGION ID(Mask::Data Members) ENABLED START -----*/

//	Add your own data members

/*----- PROTECTED REGION END -----*/	//	Mask::Data Members

//	Device property data members
public:
	//	MemorizedRunLevel:	Memorize/Define the runLevel attribute<br>
	Tango::DevULong	memorizedRunLevel;

//	Attribute data members
public:
	Tango::DevString	*attr_version_read;
	Tango::DevString	*attr_operationsList_read;
	Tango::DevShort	*attr_maskImage_read;

//	Constructors and destructors
public:
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device Name
	 */
	Mask(Tango::DeviceClass *cl,string &s);
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device Name
	 */
	Mask(Tango::DeviceClass *cl,const char *s);
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device name
	 *	@param d	Device description.
	 */
	Mask(Tango::DeviceClass *cl,const char *s,const char *d);
	/**
	 * The device object destructor.
	 */
	~Mask() {delete_device();};


//	Miscellaneous methods
public:
	/*
	 *	will be called at device destruction or at init command.
	 */
	void delete_device();
	/*
	 *	Initialize the device
	 */
	virtual void init_device();
	/*
	 *	Read the device properties from database
	 */
	void get_device_property();
	/*
	 *	Always executed method before execution command method.
	 */
	virtual void always_executed_hook();


//	Attribute methods
public:
	//--------------------------------------------------------
	/*
	 *	Method      : Mask::read_attr_hardware()
	 *	Description : Hardware acquisition for attributes.
	 */
	//--------------------------------------------------------
	virtual void read_attr_hardware(vector<long> &attr_list);
	//--------------------------------------------------------
	/*
	 *	Method      : Mask::write_attr_hardware()
	 *	Description : Hardware writing for attributes.
	 */
	//--------------------------------------------------------
	virtual void write_attr_hardware(vector<long> &attr_list);

/**
 *	Attribute version related methods
 *	Description: Display the Version of the Mask Device
 *
 *	Data type:	Tango::DevString
 *	Attr type:	Scalar
 */
	virtual void read_version(Tango::Attribute &attr);
	virtual bool is_version_allowed(Tango::AttReqType type);
/**
 *	Attribute runLevel related methods
 *	Description: Fix the execution order of this operation in the processing chain
 *
 *	Data type:	Tango::DevULong
 *	Attr type:	Scalar
 */
	virtual void write_runLevel(Tango::WAttribute &attr);
	virtual bool is_runLevel_allowed(Tango::AttReqType type);
/**
 *	Attribute operationsList related methods
 *	Description: Enumerate all Mask active 'post processing' operations on the image.
 *
 *	Data type:	Tango::DevString
 *	Attr type:	Spectrum max = 1024
 */
	virtual void read_operationsList(Tango::Attribute &attr);
	virtual bool is_operationsList_allowed(Tango::AttReqType type);
/**
 *	Attribute maskImage related methods
 *	Description: Define the mask image for the Mask Processing 
 *
 *	Data type:	Tango::DevShort
 *	Attr type:	Image max = 10000 x 10000
 */
	virtual void read_maskImage(Tango::Attribute &attr);
	virtual void write_maskImage(Tango::WAttribute &attr);
	virtual bool is_maskImage_allowed(Tango::AttReqType type);


	//--------------------------------------------------------
	/**
	 *	Method      : Mask::add_dynamic_attributes()
	 *	Description : Add dynamic attributes if any.
	 */
	//--------------------------------------------------------
	void add_dynamic_attributes();




//	Command related methods
public:
	/**
	 *	Command State related method
	 *	Description: This command gets the device state (stored in its <i>device_state</i> data member) and returns it to the caller.
	 *
	 *	@returns State Code
	 */
	virtual Tango::DevState dev_state();


	//--------------------------------------------------------
	/**
	 *	Method      : Mask::add_dynamic_commands()
	 *	Description : Add dynamic commands if any.
	 */
	//--------------------------------------------------------
	void add_dynamic_commands();

/*----- PROTECTED REGION ID(Mask::Additional Method prototypes) ENABLED START -----*/
public:
Tango::DevULong	attr_runLevel_write;
Tango::DevShort	attr_maskImage_write;
void read_runLevel(Tango::Attribute &attr);
    bool is_device_initialized()
    {
        return m_is_device_initialized;
    };

    ///methode to create the Data image needed by processlib Mask task
    template <typename OUTPUT>
    Data create_data_from_mask( Tango::DevShort* mask_image,    //mask image
                                long mask_dim_x,                //dim_x of the mask
                                long mask_dim_y,                //dim_y of the mask
                                Data::TYPE data_type,      //type of the object Data to create (Data::INT8 Data::UINT8 Data::INT16 ...)
                                long data_depth);               //number of bytes occupied by the Data::TYPE (1->Data::INT8 2->Data::INT16 ...)

    void set_mask_image(void);
protected:
    //	Add your own data members here
    //-----------------------------------------
    bool            m_is_device_initialized;
    stringstream    m_status_message;

    //LIMA objects
    lima::CtControl*            m_ct;
    lima::SoftOpInstance        m_soft_operation;
    long                        m_dim_x;
    long                        m_dim_y;
    std::vector<std::string >   m_operations_list;

/*----- PROTECTED REGION END -----*/	//	Mask::Additional Method prototypes
};

/*----- PROTECTED REGION ID(Mask::Additional Classes Definitions) ENABLED START -----*/
}
#include "Mask.hpp"
namespace Mask_ns
{

/*----- PROTECTED REGION END -----*/	//	Mask::Additional Classes Definitions

}	//	End of namespace

#endif   //	Mask_H
