/*----- PROTECTED REGION ID(RixsClass.cpp) ENABLED START -----*/
static const char *RcsId      = "$Id:  $";
static const char *TagName    = "$Name:  $";
static const char *CvsPath    = "$Source:  $";
static const char *SvnPath    = "$HeadURL:  $";
static const char *HttpServer = "http://www.esrf.eu/computing/cs/tango/tango_doc/ds_doc/";
//=============================================================================
//
// file :        RixsClass.cpp
//
// description : C++ source for the RixsClass.
//               A singleton class derived from DeviceClass.
//               It implements the command and attribute list
//               and all properties and methods required
//               by the Rixs once per process.
//
// project :     Lima Rixs Device Specific
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#include <RixsClass.h>

/*----- PROTECTED REGION END -----*/	//	RixsClass.cpp

//-------------------------------------------------------------------
/**
 *	Create RixsClass singleton and
 *	return it in a C function for Python usage
 */
//-------------------------------------------------------------------
extern "C" {
#ifdef _TG_WINDOWS_

__declspec(dllexport)

#endif

	Tango::DeviceClass *_create_Rixs_class(const char *name) {
		return Rixs_ns::RixsClass::init(name);
	}
}

namespace Rixs_ns
{
//===================================================================
//	Initialize pointer for singleton pattern
//===================================================================
RixsClass *RixsClass::_instance = NULL;

//--------------------------------------------------------
/**
 * method : 		RixsClass::RixsClass(string &s)
 * description : 	constructor for the RixsClass
 *
 * @param s	The class name
 */
//--------------------------------------------------------
RixsClass::RixsClass(string &s):Tango::DeviceClass(s)
{
	cout2 << "Entering RixsClass constructor" << endl;
	set_default_property();
	write_class_property();

	/*----- PROTECTED REGION ID(RixsClass::constructor) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	RixsClass::constructor

	cout2 << "Leaving RixsClass constructor" << endl;
}

//--------------------------------------------------------
/**
 * method : 		RixsClass::~RixsClass()
 * description : 	destructor for the RixsClass
 */
//--------------------------------------------------------
RixsClass::~RixsClass()
{
	/*----- PROTECTED REGION ID(RixsClass::destructor) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	RixsClass::destructor

	_instance = NULL;
}


//--------------------------------------------------------
/**
 * method : 		RixsClass::init
 * description : 	Create the object if not already done.
 *                  Otherwise, just return a pointer to the object
 *
 * @param	name	The class name
 */
//--------------------------------------------------------
RixsClass *RixsClass::init(const char *name)
{
	if (_instance == NULL)
	{
		try
		{
			string s(name);
			_instance = new RixsClass(s);
		}
		catch (bad_alloc &)
		{
			throw;
		}
	}
	return _instance;
}

//--------------------------------------------------------
/**
 * method : 		RixsClass::instance
 * description : 	Check if object already created,
 *                  and return a pointer to the object
 */
//--------------------------------------------------------
RixsClass *RixsClass::instance()
{
	if (_instance == NULL)
	{
		cerr << "Class is not initialised !!" << endl;
		exit(-1);
	}
	return _instance;
}



//===================================================================
//	Command execution method calls
//===================================================================
//--------------------------------------------------------
/**
 * method : 		AddOperationClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *AddOperationClass::execute(Tango::DeviceImpl *device, const CORBA::Any &in_any)
{
	cout2 << "AddOperationClass::execute(): arrived" << endl;
	Tango::DevLong argin;
	extract(in_any, argin);
	((static_cast<Rixs *>(device))->add_operation(argin));
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		RemoveOperationClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *RemoveOperationClass::execute(Tango::DeviceImpl *device, const CORBA::Any &in_any)
{
	cout2 << "RemoveOperationClass::execute(): arrived" << endl;
	Tango::DevLong argin;
	extract(in_any, argin);
	((static_cast<Rixs *>(device))->remove_operation(argin));
	return new CORBA::Any();
}


//===================================================================
//	Properties management
//===================================================================
//--------------------------------------------------------
/**
 *	Method      : RixsClass::get_class_property()
 *	Description : Get the class property for specified name.
 */
//--------------------------------------------------------
Tango::DbDatum RixsClass::get_class_property(string &prop_name)
{
	for (unsigned int i=0 ; i<cl_prop.size() ; i++)
		if (cl_prop[i].name == prop_name)
			return cl_prop[i];
	//	if not found, returns  an empty DbDatum
	return Tango::DbDatum(prop_name);
}

//--------------------------------------------------------
/**
 *	Method      : RixsClass::get_default_device_property()
 *	Description : Return the default value for device property.
 */
//--------------------------------------------------------
Tango::DbDatum RixsClass::get_default_device_property(string &prop_name)
{
	for (unsigned int i=0 ; i<dev_def_prop.size() ; i++)
		if (dev_def_prop[i].name == prop_name)
			return dev_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}

//--------------------------------------------------------
/**
 *	Method      : RixsClass::get_default_class_property()
 *	Description : Return the default value for class property.
 */
//--------------------------------------------------------
Tango::DbDatum RixsClass::get_default_class_property(string &prop_name)
{
	for (unsigned int i=0 ; i<cl_def_prop.size() ; i++)
		if (cl_def_prop[i].name == prop_name)
			return cl_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}


//--------------------------------------------------------
/**
 *	Method      : RixsClass::set_default_property()
 *	Description : Set default property (class and device) for wizard.
 *                For each property, add to wizard property name and description.
 *                If default value has been set, add it to wizard property and
 *                store it in a DbDatum.
 */
//--------------------------------------------------------
void RixsClass::set_default_property()
{
	string	prop_name;
	string	prop_desc;
	string	prop_def;
	vector<string>	vect_data;

	//	Set Default Class Properties

	//	Set Default device Properties
	prop_name = "MemorizedOperationTypes";
	prop_desc = "Memorize all operationType declared in the order to process the image.";
	prop_def  = "NONE";
	vect_data.clear();
	vect_data.push_back("NONE");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "MemorizedOperationValues";
	prop_desc = "Memorize all operationValue associated to the operationType declared in the order to process the image.";
	prop_def  = "0";
	vect_data.clear();
	vect_data.push_back("0");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "MemorizedOperationLevels";
	prop_desc = "Memorize all levels associated to the operationType declared in the order to process the image.";
	prop_def  = "0";
	vect_data.clear();
	vect_data.push_back("0");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "ResetSpectrumsAtEachFrame";
	prop_desc = "All Spectrum data wil be reset at each new Frame";
	prop_def  = "True";
	vect_data.clear();
	vect_data.push_back("True");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "DefaultValueInSpectrumsIfEmpty";
	prop_desc = "Set default value (-1) in spectrums if there is 0 Valid Clusters";
	prop_def  = "False";
	vect_data.clear();
	vect_data.push_back("False");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "RixsDrawCentroidColor";
	prop_desc = "RIXS : Define Color of centroids";
	prop_def  = "255;0;0";
	vect_data.clear();
	vect_data.push_back("255;0;0");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "RixsDrawClusterColor";
	prop_desc = "RIXS : Define Color of Clusters";
	prop_def  = "255;0;0";
	vect_data.clear();
	vect_data.push_back("255;0;0");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
}

//--------------------------------------------------------
/**
 *	Method      : RixsClass::write_class_property()
 *	Description : Set class description fields as property in database
 */
//--------------------------------------------------------
void RixsClass::write_class_property()
{
	//	First time, check if database used
	if (Tango::Util::_UseDb == false)
		return;

	Tango::DbData	data;
	string	classname = get_name();
	string	header;
	string::size_type	start, end;

	//	Put title
	Tango::DbDatum	title("ProjectTitle");
	string	str_title("Lima Rixs Device Specific");
	title << str_title;
	data.push_back(title);

	//	Put Description
	Tango::DbDatum	description("Description");
	vector<string>	str_desc;
	str_desc.push_back("Lima Device Specific for post process image");
	description << str_desc;
	data.push_back(description);

	//  Put inheritance
	Tango::DbDatum	inher_datum("InheritedFrom");
	vector<string> inheritance;
	inheritance.push_back("TANGO_BASE_CLASS");
	inher_datum << inheritance;
	data.push_back(inher_datum);

	//	Call database and and values
	get_db_class()->put_property(data);
}

//===================================================================
//	Factory methods
//===================================================================

//--------------------------------------------------------
/**
 *	Method      : RixsClass::device_factory()
 *	Description : Create the device object(s)
 *                and store them in the device list
 */
//--------------------------------------------------------
void RixsClass::device_factory(const Tango::DevVarStringArray *devlist_ptr)
{
	/*----- PROTECTED REGION ID(RixsClass::device_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	RixsClass::device_factory_before

	//	Create devices and add it into the device list
	for (unsigned long i=0 ; i<devlist_ptr->length() ; i++)
	{
		cout4 << "Device name : " << (*devlist_ptr)[i].in() << endl;
		device_list.push_back(new Rixs(this, (*devlist_ptr)[i]));
	}

	//	Manage dynamic attributes if any
	erase_dynamic_attributes(devlist_ptr, get_class_attr()->get_attr_list());

	//	Export devices to the outside world
	for (unsigned long i=1 ; i<=devlist_ptr->length() ; i++)
	{
		//	Add dynamic attributes if any
		Rixs *dev = static_cast<Rixs *>(device_list[device_list.size()-i]);
		dev->add_dynamic_attributes();

		//	Check before if database used.
		if ((Tango::Util::_UseDb == true) && (Tango::Util::_FileDb == false))
			export_device(dev);
		else
			export_device(dev, dev->get_name().c_str());
	}

	/*----- PROTECTED REGION ID(RixsClass::device_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	RixsClass::device_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : RixsClass::attribute_factory()
 *	Description : Create the attribute object(s)
 *                and store them in the attribute list
 */
//--------------------------------------------------------
void RixsClass::attribute_factory(vector<Tango::Attr *> &att_list)
{
	/*----- PROTECTED REGION ID(RixsClass::attribute_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	RixsClass::attribute_factory_before
	//	Attribute : version
	versionAttrib	*version = new versionAttrib();
	Tango::UserDefaultAttrProp	version_prop;
	version_prop.set_description("Display the Version");
	//	label	not set for version
	version_prop.set_unit(" ");
	version_prop.set_standard_unit(" ");
	version_prop.set_display_unit(" ");
	//	format	not set for version
	//	max_value	not set for version
	//	min_value	not set for version
	//	max_alarm	not set for version
	//	min_alarm	not set for version
	//	max_warning	not set for version
	//	min_warning	not set for version
	//	delta_t	not set for version
	//	delta_val	not set for version
	
	version->set_default_properties(version_prop);
	//	Not Polled
	version->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(version);

	//	Attribute : operationType
	operationTypeAttrib	*operationtype = new operationTypeAttrib();
	Tango::UserDefaultAttrProp	operationtype_prop;
	operationtype_prop.set_description("available types :<br>\nRIXS<br>\nNONE<br>");
	//	label	not set for operationType
	operationtype_prop.set_unit(" ");
	operationtype_prop.set_standard_unit(" ");
	operationtype_prop.set_display_unit(" ");
	//	format	not set for operationType
	//	max_value	not set for operationType
	//	min_value	not set for operationType
	//	max_alarm	not set for operationType
	//	min_alarm	not set for operationType
	//	max_warning	not set for operationType
	//	min_warning	not set for operationType
	//	delta_t	not set for operationType
	//	delta_val	not set for operationType
	
	operationtype->set_default_properties(operationtype_prop);
	//	Not Polled
	operationtype->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(operationtype);

	//	Attribute : operationValue
	operationValueAttrib	*operationvalue = new operationValueAttrib();
	Tango::UserDefaultAttrProp	operationvalue_prop;
	operationvalue_prop.set_description("Arithmetic available values :<br>\nany numeric value\n\n");
	//	label	not set for operationValue
	operationvalue_prop.set_unit(" ");
	//	standard_unit	not set for operationValue
	operationvalue_prop.set_display_unit(" ");
	operationvalue_prop.set_format("%s");
	//	max_value	not set for operationValue
	//	min_value	not set for operationValue
	//	max_alarm	not set for operationValue
	//	min_alarm	not set for operationValue
	//	max_warning	not set for operationValue
	//	min_warning	not set for operationValue
	//	delta_t	not set for operationValue
	//	delta_val	not set for operationValue
	
	operationvalue->set_default_properties(operationvalue_prop);
	//	Not Polled
	operationvalue->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(operationvalue);

	//	Attribute : minAreaCluster
	minAreaClusterAttrib	*minareacluster = new minAreaClusterAttrib();
	Tango::UserDefaultAttrProp	minareacluster_prop;
	minareacluster_prop.set_description("Define the Min Area accepted for a Cluster.<CR>\n-1 to disable control of Min Area");
	//	label	not set for minAreaCluster
	minareacluster_prop.set_unit(" ");
	//	standard_unit	not set for minAreaCluster
	//	display_unit	not set for minAreaCluster
	//	format	not set for minAreaCluster
	//	max_value	not set for minAreaCluster
	//	min_value	not set for minAreaCluster
	//	max_alarm	not set for minAreaCluster
	//	min_alarm	not set for minAreaCluster
	//	max_warning	not set for minAreaCluster
	//	min_warning	not set for minAreaCluster
	//	delta_t	not set for minAreaCluster
	//	delta_val	not set for minAreaCluster
	
	minareacluster->set_default_properties(minareacluster_prop);
	//	Not Polled
	minareacluster->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(minareacluster);

	//	Attribute : maxAreaCluster
	maxAreaClusterAttrib	*maxareacluster = new maxAreaClusterAttrib();
	Tango::UserDefaultAttrProp	maxareacluster_prop;
	maxareacluster_prop.set_description("Define the Max Area accepted for a Cluster.<CR>\n-1 to disable control of Max Area");
	//	label	not set for maxAreaCluster
	maxareacluster_prop.set_unit(" ");
	//	standard_unit	not set for maxAreaCluster
	//	display_unit	not set for maxAreaCluster
	//	format	not set for maxAreaCluster
	//	max_value	not set for maxAreaCluster
	//	min_value	not set for maxAreaCluster
	//	max_alarm	not set for maxAreaCluster
	//	min_alarm	not set for maxAreaCluster
	//	max_warning	not set for maxAreaCluster
	//	min_warning	not set for maxAreaCluster
	//	delta_t	not set for maxAreaCluster
	//	delta_val	not set for maxAreaCluster
	
	maxareacluster->set_default_properties(maxareacluster_prop);
	//	Not Polled
	maxareacluster->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(maxareacluster);

	//	Attribute : nbClusterValid
	nbClusterValidAttrib	*nbclustervalid = new nbClusterValidAttrib();
	Tango::UserDefaultAttrProp	nbclustervalid_prop;
	nbclustervalid_prop.set_description("Nombre of valid clusters");
	//	label	not set for nbClusterValid
	nbclustervalid_prop.set_unit(" ");
	//	standard_unit	not set for nbClusterValid
	//	display_unit	not set for nbClusterValid
	//	format	not set for nbClusterValid
	//	max_value	not set for nbClusterValid
	//	min_value	not set for nbClusterValid
	//	max_alarm	not set for nbClusterValid
	//	min_alarm	not set for nbClusterValid
	//	max_warning	not set for nbClusterValid
	//	min_warning	not set for nbClusterValid
	//	delta_t	not set for nbClusterValid
	//	delta_val	not set for nbClusterValid
	
	nbclustervalid->set_default_properties(nbclustervalid_prop);
	//	Not Polled
	nbclustervalid->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(nbclustervalid);

	//	Attribute : drawClusterEnabled
	drawClusterEnabledAttrib	*drawclusterenabled = new drawClusterEnabledAttrib();
	Tango::UserDefaultAttrProp	drawclusterenabled_prop;
	drawclusterenabled_prop.set_description("Enable/Disable drawing Rect on Valid Clusters");
	//	label	not set for drawClusterEnabled
	//	unit	not set for drawClusterEnabled
	//	standard_unit	not set for drawClusterEnabled
	//	display_unit	not set for drawClusterEnabled
	//	format	not set for drawClusterEnabled
	//	max_value	not set for drawClusterEnabled
	//	min_value	not set for drawClusterEnabled
	//	max_alarm	not set for drawClusterEnabled
	//	min_alarm	not set for drawClusterEnabled
	//	max_warning	not set for drawClusterEnabled
	//	min_warning	not set for drawClusterEnabled
	//	delta_t	not set for drawClusterEnabled
	//	delta_val	not set for drawClusterEnabled
	
	drawclusterenabled->set_default_properties(drawclusterenabled_prop);
	//	Not Polled
	drawclusterenabled->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(drawclusterenabled);

	//	Attribute : drawCentroidEnabled
	drawCentroidEnabledAttrib	*drawcentroidenabled = new drawCentroidEnabledAttrib();
	Tango::UserDefaultAttrProp	drawcentroidenabled_prop;
	drawcentroidenabled_prop.set_description("Enable/Disable drawing Circle on Centroids of Valid Clusters");
	//	label	not set for drawCentroidEnabled
	//	unit	not set for drawCentroidEnabled
	//	standard_unit	not set for drawCentroidEnabled
	//	display_unit	not set for drawCentroidEnabled
	//	format	not set for drawCentroidEnabled
	//	max_value	not set for drawCentroidEnabled
	//	min_value	not set for drawCentroidEnabled
	//	max_alarm	not set for drawCentroidEnabled
	//	min_alarm	not set for drawCentroidEnabled
	//	max_warning	not set for drawCentroidEnabled
	//	min_warning	not set for drawCentroidEnabled
	//	delta_t	not set for drawCentroidEnabled
	//	delta_val	not set for drawCentroidEnabled
	
	drawcentroidenabled->set_default_properties(drawcentroidenabled_prop);
	//	Not Polled
	drawcentroidenabled->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(drawcentroidenabled);

	//	Attribute : pngFilesEnabled
	pngFilesEnabledAttrib	*pngfilesenabled = new pngFilesEnabledAttrib();
	Tango::UserDefaultAttrProp	pngfilesenabled_prop;
	pngfilesenabled_prop.set_description("Enable/Disable writing results in PNG files");
	//	label	not set for pngFilesEnabled
	pngfilesenabled_prop.set_unit(" ");
	//	standard_unit	not set for pngFilesEnabled
	//	display_unit	not set for pngFilesEnabled
	//	format	not set for pngFilesEnabled
	//	max_value	not set for pngFilesEnabled
	//	min_value	not set for pngFilesEnabled
	//	max_alarm	not set for pngFilesEnabled
	//	min_alarm	not set for pngFilesEnabled
	//	max_warning	not set for pngFilesEnabled
	//	min_warning	not set for pngFilesEnabled
	//	delta_t	not set for pngFilesEnabled
	//	delta_val	not set for pngFilesEnabled
	
	pngfilesenabled->set_default_properties(pngfilesenabled_prop);
	//	Not Polled
	pngfilesenabled->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(pngfilesenabled);

	//	Attribute : pngFilesPath
	pngFilesPathAttrib	*pngfilespath = new pngFilesPathAttrib();
	Tango::UserDefaultAttrProp	pngfilespath_prop;
	pngfilespath_prop.set_description("Path of PNG files ");
	//	label	not set for pngFilesPath
	pngfilespath_prop.set_unit(" ");
	//	standard_unit	not set for pngFilesPath
	//	display_unit	not set for pngFilesPath
	//	format	not set for pngFilesPath
	//	max_value	not set for pngFilesPath
	//	min_value	not set for pngFilesPath
	//	max_alarm	not set for pngFilesPath
	//	min_alarm	not set for pngFilesPath
	//	max_warning	not set for pngFilesPath
	//	min_warning	not set for pngFilesPath
	//	delta_t	not set for pngFilesPath
	//	delta_val	not set for pngFilesPath
	
	pngfilespath->set_default_properties(pngfilespath_prop);
	//	Not Polled
	pngfilespath->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(pngfilespath);

	//	Attribute : operationsList
	operationsListAttrib	*operationslist = new operationsListAttrib();
	Tango::UserDefaultAttrProp	operationslist_prop;
	operationslist_prop.set_description("Enumerate all Rixs active 'post processing' operations on the image.");
	//	label	not set for operationsList
	operationslist_prop.set_unit(" ");
	operationslist_prop.set_standard_unit(" ");
	operationslist_prop.set_display_unit(" ");
	//	format	not set for operationsList
	//	max_value	not set for operationsList
	//	min_value	not set for operationsList
	//	max_alarm	not set for operationsList
	//	min_alarm	not set for operationsList
	//	max_warning	not set for operationsList
	//	min_warning	not set for operationsList
	//	delta_t	not set for operationsList
	//	delta_val	not set for operationsList
	
	operationslist->set_default_properties(operationslist_prop);
	//	Not Polled
	operationslist->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(operationslist);

	//	Attribute : clusterCounter
	clusterCounterAttrib	*clustercounter = new clusterCounterAttrib();
	Tango::UserDefaultAttrProp	clustercounter_prop;
	//	description	not set for clusterCounter
	//	label	not set for clusterCounter
	clustercounter_prop.set_unit(" ");
	clustercounter_prop.set_standard_unit(" ");
	//	display_unit	not set for clusterCounter
	//	format	not set for clusterCounter
	//	max_value	not set for clusterCounter
	//	min_value	not set for clusterCounter
	//	max_alarm	not set for clusterCounter
	//	min_alarm	not set for clusterCounter
	//	max_warning	not set for clusterCounter
	//	min_warning	not set for clusterCounter
	//	delta_t	not set for clusterCounter
	//	delta_val	not set for clusterCounter
	
	clustercounter->set_default_properties(clustercounter_prop);
	//	Not Polled
	clustercounter->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(clustercounter);

	//	Attribute : clusterArea
	clusterAreaAttrib	*clusterarea = new clusterAreaAttrib();
	Tango::UserDefaultAttrProp	clusterarea_prop;
	//	description	not set for clusterArea
	//	label	not set for clusterArea
	clusterarea_prop.set_unit(" ");
	clusterarea_prop.set_standard_unit(" ");
	clusterarea_prop.set_display_unit(" ");
	//	format	not set for clusterArea
	//	max_value	not set for clusterArea
	//	min_value	not set for clusterArea
	//	max_alarm	not set for clusterArea
	//	min_alarm	not set for clusterArea
	//	max_warning	not set for clusterArea
	//	min_warning	not set for clusterArea
	//	delta_t	not set for clusterArea
	//	delta_val	not set for clusterArea
	
	clusterarea->set_default_properties(clusterarea_prop);
	//	Not Polled
	clusterarea->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(clusterarea);

	//	Attribute : clusterSum
	clusterSumAttrib	*clustersum = new clusterSumAttrib();
	Tango::UserDefaultAttrProp	clustersum_prop;
	//	description	not set for clusterSum
	//	label	not set for clusterSum
	clustersum_prop.set_unit(" ");
	clustersum_prop.set_standard_unit(" ");
	clustersum_prop.set_display_unit(" ");
	//	format	not set for clusterSum
	//	max_value	not set for clusterSum
	//	min_value	not set for clusterSum
	//	max_alarm	not set for clusterSum
	//	min_alarm	not set for clusterSum
	//	max_warning	not set for clusterSum
	//	min_warning	not set for clusterSum
	//	delta_t	not set for clusterSum
	//	delta_val	not set for clusterSum
	
	clustersum->set_default_properties(clustersum_prop);
	//	Not Polled
	clustersum->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(clustersum);

	//	Attribute : clusterCentroidX
	clusterCentroidXAttrib	*clustercentroidx = new clusterCentroidXAttrib();
	Tango::UserDefaultAttrProp	clustercentroidx_prop;
	//	description	not set for clusterCentroidX
	//	label	not set for clusterCentroidX
	clustercentroidx_prop.set_unit(" ");
	clustercentroidx_prop.set_standard_unit(" ");
	clustercentroidx_prop.set_display_unit(" ");
	//	format	not set for clusterCentroidX
	//	max_value	not set for clusterCentroidX
	//	min_value	not set for clusterCentroidX
	//	max_alarm	not set for clusterCentroidX
	//	min_alarm	not set for clusterCentroidX
	//	max_warning	not set for clusterCentroidX
	//	min_warning	not set for clusterCentroidX
	//	delta_t	not set for clusterCentroidX
	//	delta_val	not set for clusterCentroidX
	
	clustercentroidx->set_default_properties(clustercentroidx_prop);
	//	Not Polled
	clustercentroidx->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(clustercentroidx);

	//	Attribute : clusterCentroidY
	clusterCentroidYAttrib	*clustercentroidy = new clusterCentroidYAttrib();
	Tango::UserDefaultAttrProp	clustercentroidy_prop;
	//	description	not set for clusterCentroidY
	//	label	not set for clusterCentroidY
	clustercentroidy_prop.set_unit(" ");
	clustercentroidy_prop.set_standard_unit(" ");
	clustercentroidy_prop.set_display_unit(" ");
	//	format	not set for clusterCentroidY
	//	max_value	not set for clusterCentroidY
	//	min_value	not set for clusterCentroidY
	//	max_alarm	not set for clusterCentroidY
	//	min_alarm	not set for clusterCentroidY
	//	max_warning	not set for clusterCentroidY
	//	min_warning	not set for clusterCentroidY
	//	delta_t	not set for clusterCentroidY
	//	delta_val	not set for clusterCentroidY
	
	clustercentroidy->set_default_properties(clustercentroidy_prop);
	//	Not Polled
	clustercentroidy->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(clustercentroidy);


	//	Create a list of static attributes
	create_static_attribute_list(get_class_attr()->get_attr_list());
	/*----- PROTECTED REGION ID(RixsClass::attribute_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	RixsClass::attribute_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : RixsClass::pipe_factory()
 *	Description : Create the pipe object(s)
 *                and store them in the pipe list
 */
//--------------------------------------------------------
void RixsClass::pipe_factory()
{
	/*----- PROTECTED REGION ID(RixsClass::pipe_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	RixsClass::pipe_factory_before
	/*----- PROTECTED REGION ID(RixsClass::pipe_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	RixsClass::pipe_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : RixsClass::command_factory()
 *	Description : Create the command object(s)
 *                and store them in the command list
 */
//--------------------------------------------------------
void RixsClass::command_factory()
{
	/*----- PROTECTED REGION ID(RixsClass::command_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	RixsClass::command_factory_before


	//	Command AddOperation
	AddOperationClass	*pAddOperationCmd =
		new AddOperationClass("AddOperation",
			Tango::DEV_LONG, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pAddOperationCmd);

	//	Command RemoveOperation
	RemoveOperationClass	*pRemoveOperationCmd =
		new RemoveOperationClass("RemoveOperation",
			Tango::DEV_LONG, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pRemoveOperationCmd);

	/*----- PROTECTED REGION ID(RixsClass::command_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	RixsClass::command_factory_after
}

//===================================================================
//	Dynamic attributes related methods
//===================================================================

//--------------------------------------------------------
/**
 * method : 		RixsClass::create_static_attribute_list
 * description : 	Create the a list of static attributes
 *
 * @param	att_list	the ceated attribute list
 */
//--------------------------------------------------------
void RixsClass::create_static_attribute_list(vector<Tango::Attr *> &att_list)
{
	for (unsigned long i=0 ; i<att_list.size() ; i++)
	{
		string att_name(att_list[i]->get_name());
		transform(att_name.begin(), att_name.end(), att_name.begin(), ::tolower);
		defaultAttList.push_back(att_name);
	}

	cout2 << defaultAttList.size() << " attributes in default list" << endl;

	/*----- PROTECTED REGION ID(RixsClass::create_static_att_list) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	RixsClass::create_static_att_list
}


//--------------------------------------------------------
/**
 * method : 		RixsClass::erase_dynamic_attributes
 * description : 	delete the dynamic attributes if any.
 *
 * @param	devlist_ptr	the device list pointer
 * @param	list of all attributes
 */
//--------------------------------------------------------
void RixsClass::erase_dynamic_attributes(const Tango::DevVarStringArray *devlist_ptr, vector<Tango::Attr *> &att_list)
{
	Tango::Util *tg = Tango::Util::instance();

	for (unsigned long i=0 ; i<devlist_ptr->length() ; i++)
	{
		Tango::DeviceImpl *dev_impl = tg->get_device_by_name(((string)(*devlist_ptr)[i]).c_str());
		Rixs *dev = static_cast<Rixs *> (dev_impl);

		vector<Tango::Attribute *> &dev_att_list = dev->get_device_attr()->get_attribute_list();
		vector<Tango::Attribute *>::iterator ite_att;
		for (ite_att=dev_att_list.begin() ; ite_att != dev_att_list.end() ; ++ite_att)
		{
			string att_name((*ite_att)->get_name_lower());
			if ((att_name == "state") || (att_name == "status"))
				continue;
			vector<string>::iterator ite_str = find(defaultAttList.begin(), defaultAttList.end(), att_name);
			if (ite_str == defaultAttList.end())
			{
				cout2 << att_name << " is a UNWANTED dynamic attribute for device " << (*devlist_ptr)[i] << endl;
				Tango::Attribute &att = dev->get_device_attr()->get_attr_by_name(att_name.c_str());
				dev->remove_attribute(att_list[att.get_attr_idx()], true, false);
				--ite_att;
			}
		}
	}
	/*----- PROTECTED REGION ID(RixsClass::erase_dynamic_attributes) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	RixsClass::erase_dynamic_attributes
}

//--------------------------------------------------------
/**
 *	Method      : RixsClass::get_attr_object_by_name()
 *	Description : returns Tango::Attr * object found by name
 */
//--------------------------------------------------------
Tango::Attr *RixsClass::get_attr_object_by_name(vector<Tango::Attr *> &att_list, string attname)
{
	vector<Tango::Attr *>::iterator it;
	for (it=att_list.begin() ; it<att_list.end() ; ++it)
		if ((*it)->get_name()==attname)
			return (*it);
	//	Attr does not exist
	return NULL;
}


/*----- PROTECTED REGION ID(RixsClass::Additional Methods) ENABLED START -----*/

/*----- PROTECTED REGION END -----*/	//	RixsClass::Additional Methods
} //	namespace
