/*----- PROTECTED REGION ID(LambdaClass.h) ENABLED START -----*/
//=============================================================================
//
// file :        LambdaClass.h
//
// description : Include for the Lambda root class.
//               This class is the singleton class for
//                the Lambda device class.
//               It contains all properties and methods which the 
//               Lambda requires only once e.g. the commands.
//
// project :     Sls dectector TANGO specific device.
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#ifndef LambdaClass_H
#define LambdaClass_H

#include <tango.h>
#include <Lambda.h>


/*----- PROTECTED REGION END -----*/	//	LambdaClass.h


namespace Lambda_ns
{
/*----- PROTECTED REGION ID(LambdaClass::classes for dynamic creation) ENABLED START -----*/


/*----- PROTECTED REGION END -----*/	//	LambdaClass::classes for dynamic creation

//=========================================
//	Define classes for attributes
//=========================================
//	Attribute configFilesPath class definition
class configFilesPathAttrib: public Tango::Attr
{
public:
	configFilesPathAttrib():Attr("configFilesPath",
			Tango::DEV_STRING, Tango::READ) {};
	~configFilesPathAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<Lambda *>(dev))->read_configFilesPath(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<Lambda *>(dev))->is_configFilesPath_allowed(ty);}
};

//	Attribute readoutTime class definition
class readoutTimeAttrib: public Tango::Attr
{
public:
	readoutTimeAttrib():Attr("readoutTime",
			Tango::DEV_FLOAT, Tango::READ) {};
	~readoutTimeAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<Lambda *>(dev))->read_readoutTime(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<Lambda *>(dev))->is_readoutTime_allowed(ty);}
};

//	Attribute distortionCorrection class definition
class distortionCorrectionAttrib: public Tango::Attr
{
public:
	distortionCorrectionAttrib():Attr("distortionCorrection",
			Tango::DEV_BOOLEAN, Tango::READ) {};
	~distortionCorrectionAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<Lambda *>(dev))->read_distortionCorrection(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<Lambda *>(dev))->is_distortionCorrection_allowed(ty);}
};

//	Attribute energyThreshold1 class definition
class energyThreshold1Attrib: public Tango::Attr
{
public:
	energyThreshold1Attrib():Attr("energyThreshold1",
			Tango::DEV_FLOAT, Tango::READ_WRITE) {};
	~energyThreshold1Attrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<Lambda *>(dev))->read_energyThreshold1(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<Lambda *>(dev))->write_energyThreshold1(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<Lambda *>(dev))->is_energyThreshold1_allowed(ty);}
};

//	Attribute operatingMode class definition
class operatingModeAttrib: public Tango::Attr
{
public:
	operatingModeAttrib():Attr("operatingMode",
			Tango::DEV_STRING, Tango::READ) {};
	~operatingModeAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<Lambda *>(dev))->read_operatingMode(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<Lambda *>(dev))->is_operatingMode_allowed(ty);}
};

//	Attribute burstMode class definition
class burstModeAttrib: public Tango::Attr
{
public:
	burstModeAttrib():Attr("burstMode",
			Tango::DEV_BOOLEAN, Tango::READ) {};
	~burstModeAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<Lambda *>(dev))->read_burstMode(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<Lambda *>(dev))->is_burstMode_allowed(ty);}
};


/**
 *	The LambdaClass singleton definition
 */

#ifdef _TG_WINDOWS_
class __declspec(dllexport)  LambdaClass : public Tango::DeviceClass
#else
class LambdaClass : public Tango::DeviceClass
#endif
{
	/*----- PROTECTED REGION ID(LambdaClass::Additionnal DServer data members) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	LambdaClass::Additionnal DServer data members

	public:
		//	write class properties data members
		Tango::DbData	cl_prop;
		Tango::DbData	cl_def_prop;
		Tango::DbData	dev_def_prop;
	
		//	Method prototypes
		static LambdaClass *init(const char *);
		static LambdaClass *instance();
		~LambdaClass();
		Tango::DbDatum	get_class_property(string &);
		Tango::DbDatum	get_default_device_property(string &);
		Tango::DbDatum	get_default_class_property(string &);
	
	protected:
		LambdaClass(string &);
		static LambdaClass *_instance;
		void command_factory();
		void attribute_factory(vector<Tango::Attr *> &);
		void write_class_property();
		void set_default_property();
		void get_class_property();
		string get_cvstag();
		string get_cvsroot();
	
	private:
		void device_factory(const Tango::DevVarStringArray *);
		void create_static_attribute_list(vector<Tango::Attr *> &);
		void erase_dynamic_attributes(const Tango::DevVarStringArray *,vector<Tango::Attr *> &);
		vector<string>	defaultAttList;
		Tango::Attr *get_attr_object_by_name(vector<Tango::Attr *> &att_list, string attname);
};

}	//	End of namespace

#endif   //	Lambda_H
