//=============================================================================
//
// file :         RoiCountersClass.h
//
// description :  Include for the RoiCountersClass root class.
//                This class is the singleton class for
//                the RoiCounters device class.
//                It contains all properties and methods which the 
//                RoiCounters requires only once e.g. the commands.
//			
// project :      TANGO Device Server
//
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// SVN only:
// $HeadURL: $
//
// CVS only:
// $Source:  $
// $Log:  $
//
// copyleft :     European Synchrotron Radiation Facility
//                BP 220, Grenoble 38043
//                FRANCE
//
//=============================================================================
//
//  		This file is generated by POGO
//	(Program Obviously used to Generate tango Object)
//
//         (c) - Software Engineering Group - ESRF
//=============================================================================

#ifndef _ROICOUNTERSCLASS_H
#define _ROICOUNTERSCLASS_H

#ifdef WIN32
#include <tango.h>
#endif

#include <RoiCounters.h>

#ifndef WIN32
#include <tango.h>
#endif

namespace RoiCounters_ns
{//=====================================
//	Define classes for attributes
//=====================================
class versionAttrib: public Tango::Attr
{
public:
	versionAttrib():Attr("version", Tango::DEV_STRING, Tango::READ) {};
	~versionAttrib() {};
	
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
	{(static_cast<RoiCounters *>(dev))->read_version(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
	{return (static_cast<RoiCounters *>(dev))->is_version_allowed(ty);}
};

//=========================================
//	Define classes for commands
//=========================================
//
// The RoiCountersClass singleton definition
//

class
#ifdef WIN32
	__declspec(dllexport)
#endif
	RoiCountersClass : public Tango::DeviceClass
{
public:
//	properties member data

//	add your own data members here
//------------------------------------

public:
	Tango::DbData	cl_prop;
	Tango::DbData	cl_def_prop;
	Tango::DbData	dev_def_prop;

//	Method prototypes
	static RoiCountersClass *init(const char *);
	static RoiCountersClass *instance();
	~RoiCountersClass();
	Tango::DbDatum	get_class_property(string &);
	Tango::DbDatum	get_default_device_property(string &);
	Tango::DbDatum	get_default_class_property(string &);
	
protected:
	RoiCountersClass(string &);
	static RoiCountersClass *_instance;
	void command_factory();
	void get_class_property();
	void attribute_factory(vector<Tango::Attr *> &);
	void write_class_property();
	void set_default_property();
	string get_cvstag();
	string get_cvsroot();

private:
	void device_factory(const Tango::DevVarStringArray *);
};


}	//	namespace RoiCounters_ns

#endif // _ROICOUNTERSCLASS_H
