/*----- PROTECTED REGION ID(LimaDetectorClass.cpp) ENABLED START -----*/
static const char *RcsId      = "$Id:  $";
static const char *TagName    = "$Name:  $";
static const char *CvsPath    = "$Source:  $";
static const char *SvnPath    = "$HeadURL:  $";
static const char *HttpServer = "http://www.esrf.eu/computing/cs/tango/tango_doc/ds_doc/";
//=============================================================================
//
// file :        LimaDetectorClass.cpp
//
// description : C++ source for the LimaDetectorClass.
//               A singleton class derived from DeviceClass.
//               It implements the command and attribute list
//               and all properties and methods required
//               by the LimaDetector once per process.
//
// project :     Lima Device Generic
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#include <LimaDetectorClass.h>

/*----- PROTECTED REGION END -----*/	//	LimaDetectorClass.cpp

//-------------------------------------------------------------------
/**
 *	Create LimaDetectorClass singleton and
 *	return it in a C function for Python usage
 */
//-------------------------------------------------------------------
extern "C" {
#ifdef _TG_WINDOWS_

__declspec(dllexport)

#endif

	Tango::DeviceClass *_create_LimaDetector_class(const char *name) {
		return LimaDetector_ns::LimaDetectorClass::init(name);
	}
}

namespace LimaDetector_ns
{
//===================================================================
//	Initialize pointer for singleton pattern
//===================================================================
LimaDetectorClass *LimaDetectorClass::_instance = NULL;

//--------------------------------------------------------
/**
 * method : 		LimaDetectorClass::LimaDetectorClass(string &s)
 * description : 	constructor for the LimaDetectorClass
 *
 * @param s	The class name
 */
//--------------------------------------------------------
LimaDetectorClass::LimaDetectorClass(string &s):Tango::DeviceClass(s)
{
	cout2 << "Entering LimaDetectorClass constructor" << endl;
	set_default_property();
	write_class_property();

	/*----- PROTECTED REGION ID(LimaDetectorClass::constructor) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LimaDetectorClass::constructor

	cout2 << "Leaving LimaDetectorClass constructor" << endl;
}

//--------------------------------------------------------
/**
 * method : 		LimaDetectorClass::~LimaDetectorClass()
 * description : 	destructor for the LimaDetectorClass
 */
//--------------------------------------------------------
LimaDetectorClass::~LimaDetectorClass()
{
	/*----- PROTECTED REGION ID(LimaDetectorClass::destructor) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LimaDetectorClass::destructor

	_instance = NULL;
}


//--------------------------------------------------------
/**
 * method : 		LimaDetectorClass::init
 * description : 	Create the object if not already done.
 *                  Otherwise, just return a pointer to the object
 *
 * @param	name	The class name
 */
//--------------------------------------------------------
LimaDetectorClass *LimaDetectorClass::init(const char *name)
{
	if (_instance == NULL)
	{
		try
		{
			string s(name);
			_instance = new LimaDetectorClass(s);
		}
		catch (bad_alloc &)
		{
			throw;
		}
	}
	return _instance;
}

//--------------------------------------------------------
/**
 * method : 		LimaDetectorClass::instance
 * description : 	Check if object already created,
 *                  and return a pointer to the object
 */
//--------------------------------------------------------
LimaDetectorClass *LimaDetectorClass::instance()
{
	if (_instance == NULL)
	{
		cerr << "Class is not initialised !!" << endl;
		exit(-1);
	}
	return _instance;
}



//===================================================================
//	Command execution method calls
//===================================================================
//--------------------------------------------------------
/**
 * method : 		PrepareClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *PrepareClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "PrepareClass::execute(): arrived" << endl;
	((static_cast<LimaDetector *>(device))->prepare());
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		SnapClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *SnapClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "SnapClass::execute(): arrived" << endl;
	((static_cast<LimaDetector *>(device))->snap());
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		StartClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *StartClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "StartClass::execute(): arrived" << endl;
	((static_cast<LimaDetector *>(device))->start());
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		StopClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *StopClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "StopClass::execute(): arrived" << endl;
	((static_cast<LimaDetector *>(device))->stop());
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		SetROIClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *SetROIClass::execute(Tango::DeviceImpl *device, const CORBA::Any &in_any)
{
	cout2 << "SetROIClass::execute(): arrived" << endl;
	const Tango::DevVarULongArray *argin;
	extract(in_any, argin);
	((static_cast<LimaDetector *>(device))->set_roi(argin));
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		SetBinningClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *SetBinningClass::execute(Tango::DeviceImpl *device, const CORBA::Any &in_any)
{
	cout2 << "SetBinningClass::execute(): arrived" << endl;
	const Tango::DevVarULongArray *argin;
	extract(in_any, argin);
	((static_cast<LimaDetector *>(device))->set_binning(argin));
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		ResetBinningClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *ResetBinningClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "ResetBinningClass::execute(): arrived" << endl;
	((static_cast<LimaDetector *>(device))->reset_binning());
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		ResetROIClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *ResetROIClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "ResetROIClass::execute(): arrived" << endl;
	((static_cast<LimaDetector *>(device))->reset_roi());
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		GetAttributeAvailableValuesClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *GetAttributeAvailableValuesClass::execute(Tango::DeviceImpl *device, const CORBA::Any &in_any)
{
	cout2 << "GetAttributeAvailableValuesClass::execute(): arrived" << endl;
	Tango::DevString argin;
	extract(in_any, argin);
	return insert((static_cast<LimaDetector *>(device))->get_attribute_available_values(argin));
}

//--------------------------------------------------------
/**
 * method : 		GetAvailableCapabilitiesClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *GetAvailableCapabilitiesClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "GetAvailableCapabilitiesClass::execute(): arrived" << endl;
	return insert((static_cast<LimaDetector *>(device))->get_available_capabilities());
}

//--------------------------------------------------------
/**
 * method : 		ResetFileIndexClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *ResetFileIndexClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "ResetFileIndexClass::execute(): arrived" << endl;
	((static_cast<LimaDetector *>(device))->reset_file_index());
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		ReloadROIClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *ReloadROIClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "ReloadROIClass::execute(): arrived" << endl;
	((static_cast<LimaDetector *>(device))->reload_roi());
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		GetDataStreamsClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *GetDataStreamsClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "GetDataStreamsClass::execute(): arrived" << endl;
	return insert((static_cast<LimaDetector *>(device))->get_data_streams());
}

//--------------------------------------------------------
/**
 * method : 		InitInterfaceClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *InitInterfaceClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "InitInterfaceClass::execute(): arrived" << endl;
	((static_cast<LimaDetector *>(device))->init_interface());
	return new CORBA::Any();
}


//===================================================================
//	Properties management
//===================================================================
//--------------------------------------------------------
/**
 *	Method      : LimaDetectorClass::get_class_property()
 *	Description : Get the class property for specified name.
 */
//--------------------------------------------------------
Tango::DbDatum LimaDetectorClass::get_class_property(string &prop_name)
{
	for (unsigned int i=0 ; i<cl_prop.size() ; i++)
		if (cl_prop[i].name == prop_name)
			return cl_prop[i];
	//	if not found, returns  an empty DbDatum
	return Tango::DbDatum(prop_name);
}

//--------------------------------------------------------
/**
 *	Method      : LimaDetectorClass::get_default_device_property()
 *	Description : Return the default value for device property.
 */
//--------------------------------------------------------
Tango::DbDatum LimaDetectorClass::get_default_device_property(string &prop_name)
{
	for (unsigned int i=0 ; i<dev_def_prop.size() ; i++)
		if (dev_def_prop[i].name == prop_name)
			return dev_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}

//--------------------------------------------------------
/**
 *	Method      : LimaDetectorClass::get_default_class_property()
 *	Description : Return the default value for class property.
 */
//--------------------------------------------------------
Tango::DbDatum LimaDetectorClass::get_default_class_property(string &prop_name)
{
	for (unsigned int i=0 ; i<cl_def_prop.size() ; i++)
		if (cl_def_prop[i].name == prop_name)
			return cl_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}


//--------------------------------------------------------
/**
 *	Method      : LimaDetectorClass::set_default_property()
 *	Description : Set default property (class and device) for wizard.
 *                For each property, add to wizard property name and description.
 *                If default value has been set, add it to wizard property and
 *                store it in a DbDatum.
 */
//--------------------------------------------------------
void LimaDetectorClass::set_default_property()
{
	string	prop_name;
	string	prop_desc;
	string	prop_def;
	vector<string>	vect_data;

	//	Set Default Class Properties

	//	Set Default device Properties
	prop_name = "AutoSaveResetRoi";
	prop_desc = "Memorize the ``full frame`` automatically at the call of ``ResetRoi`` :<br>\n[default = false]";
	prop_def  = "false";
	vect_data.clear();
	vect_data.push_back("false");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "AutoStartVideo";
	prop_desc = "Allows calling automatically the ``Start`` command when:<br>\n- The device starts.<br>\n- After calling the ``Init`` command.";
	prop_def  = "false";
	vect_data.clear();
	vect_data.push_back("false");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "DebugFormats";
	prop_desc = "Define Lima traces format.<BR>\nAvailables values :<BR>\n- DateTime<BR>\n- Thread<BR>\n- Module<BR>\n- Obj<BR>\n- Funct<BR>\n- FileLine<BR>";
	prop_def  = "DateTime\nModule\nType\nFunct";
	vect_data.clear();
	vect_data.push_back("DateTime");
	vect_data.push_back("Module");
	vect_data.push_back("Type");
	vect_data.push_back("Funct");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "DebugLevels";
	prop_desc = "Define Lima verbose level of traces.<BR>\nAvailables values :<BR>\n- Fatal<BR>\n- Error<BR>\n- Warning<BR>\n- Trace<BR>\n- Funct<BR>\n- Param<BR>\n- Return<BR>\n- Always<BR>";
	prop_def  = "Fatal\nError\nWarning";
	vect_data.clear();
	vect_data.push_back("Fatal");
	vect_data.push_back("Error");
	vect_data.push_back("Warning");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "DebugModules";
	prop_desc = "Define modules that we need to have some debug traces.<BR>\nAvailables values :<BR>\n- None<BR>\n- Hardware<BR>\n- Control<BR>\n- Common<BR>\n- Camera<BR>";
	prop_def  = "Hardware\nControl\nCommon\nCamera";
	vect_data.clear();
	vect_data.push_back("Hardware");
	vect_data.push_back("Control");
	vect_data.push_back("Common");
	vect_data.push_back("Camera");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "DetectorDescription";
	prop_desc = "Detector user-defined text to identify the engine.";
	prop_def  = "This is my Simulator";
	vect_data.clear();
	vect_data.push_back("This is my Simulator");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "DetectorPixelDepth";
	prop_desc = "Define the pixel depth of the detector : <br>\nAvailables values : <br>\n- 8 <br>\n- 12<br>\n- 16<br>\n- 16S<br>\n- 24<br>\n- 24S<br>\n- 32<br>\n- 32S<br>";
	prop_def  = "16";
	vect_data.clear();
	vect_data.push_back("16");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "DetectorType";
	prop_desc = "Define the type of the connected Detector .<BR>\nAvailables types :<BR>\n- AndorCCD<BR>\n- BaslerCCD<BR>\n- Dhyana<br>\n- Eiger<br>\n- Hamamatsu<br>\n- ImXpad<br>\n- Lambda<br>\n- MarCCD<BR>\n- Maxipix<BR>\n- Merlin<BR>\n- Pco<BR>\n- PerkinElmer<BR>\n- PilatusPixelDetector<BR>\n- PrincetonCCD<BR>\n- TeledynePI<BR>\n- SimulatorCCD<BR>\n- SlsEiger<BR>\n- SlsJungfrau<BR>\n- SpectralInstrument<BR>\n- SpectrumOneCCD<BR>\n- Ufxc<BR>\n- UviewCCD<BR>\n- XpadPixelDetector<BR>";
	prop_def  = "SimulatorCCD";
	vect_data.clear();
	vect_data.push_back("SimulatorCCD");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "DetectorVideoMode";
	prop_desc = "Define the format of video stream: <br>\nAvailables values :<br>\n- NONE<BR>\n- Y8 <BR>\n- Y16<BR>\n- Y32<BR>\n- Y64<BR>\n- RGB555<BR>\n- RGB565<BR>\n- RGB24<BR>\n- RGB32<BR>\n- BGR24<BR>\n- BGR32<BR>\n- BAYER_RG8<BR>\n- BAYER_RG16<BR>\n- I420<BR>\n- YUV411<BR>\n- YUV422<BR>\n- YUV444<BR>\n<br>\nNota:<br>\nThis property is usefull only for detectors having video capabilities.<BR>\nOtherwise, use only NONE.";
	prop_def  = "NONE";
	vect_data.clear();
	vect_data.push_back("NONE");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "ExpertAllowHwVideoExposureTime";
	prop_desc = "Enables the direct writing of exposureTime to the hardware when operating in Video mode.";
	prop_def  = "false";
	vect_data.clear();
	vect_data.push_back("false");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "ExpertAllowMixedRoiBinning";
	prop_desc = "Define whether the simultaneous use of binning and ROI is allowed";
	prop_def  = "true";
	vect_data.clear();
	vect_data.push_back("true");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "ExpertBufferMaxMemoryPercent";
	prop_desc = "Define the Percent of Memory reserved to Lima buffer control.<br>\nBufferMaxMemoryPercent = 70, allow a Memory of 1.4 Go. (Default)<br>\nBufferMaxMemoryPercent = 100, allow a Memory of 2 Go. (Maximum)";
	prop_def  = "70";
	vect_data.clear();
	vect_data.push_back("70");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "ExpertEnableHardwareSync";
	prop_desc = "Define if the device should read hardware values";
	prop_def  = "false";
	vect_data.clear();
	vect_data.push_back("false");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "ExpertNbPoolThread";
	prop_desc = "Defines the number of threads dedicated to process images in the ProcessLib";
	prop_def  = "4";
	vect_data.clear();
	vect_data.push_back("4");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "ExpertTimeoutCmd";
	prop_desc = "Define the Timeout (in ms) for some commands (snap/start/stop/prepare).<br>";
	prop_def  = "5000";
	vect_data.clear();
	vect_data.push_back("5000");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "FileFormat";
	prop_desc = "Define the format of image files :<BR>\nAvailables values :<br>\n- EDF<BR>\n- NXS<BR>\n- RAW<BR>";
	prop_def  = "NXS";
	vect_data.clear();
	vect_data.push_back("NXS");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "FileIndexPattern";
	prop_desc = "Define the pattern of the index used for image files names.<br>\n<br>\nNota :<br>\n%04d mean that file name index will be end with exactly  4 digits filled by `0` if necessary .<br>";
	prop_def  = "%06d";
	vect_data.clear();
	vect_data.push_back("%06d");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "FileManagedMode";
	prop_desc = "Define the File managed Mode :<br>\n- HARDWARE : <br>\n- SOFTWARE  : <br>";
	prop_def  = "SOFTWARE";
	vect_data.clear();
	vect_data.push_back("SOFTWARE");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "FileMemoryMode";
	prop_desc = "Available only for Nexus format : set the SetDataItemMemoryMode().<br>\nAvailable values :<br>\n- COPY<br>\n- NO_COPY";
	prop_def  = "COPY";
	vect_data.clear();
	vect_data.push_back("COPY");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "FileNbFrames";
	prop_desc = "Define the nombre of frames to push in each saving file.";
	prop_def  = "1";
	vect_data.clear();
	vect_data.push_back("1");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "FilePrefix";
	prop_desc = "Define the prefix used for the image files name.";
	prop_def  = "Image";
	vect_data.clear();
	vect_data.push_back("Image");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "FileTargetPath";
	prop_desc = "Define the Path where Files will be generated, only when savingFile is checked.";
	prop_def  = "./data";
	vect_data.clear();
	vect_data.push_back("./data");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "FileTimestampEnabled";
	prop_desc = "Define wether the timestamp is requested in the Nexus file or not<br>";
	prop_def  = "true";
	vect_data.clear();
	vect_data.push_back("true");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "FileWriteMode";
	prop_desc = "Available only for Nexus format : set the SetWriteMode(). <br>\nAvailable values :<br>\n- ASYNCHRONOUS<br>\n- SYNCHRONOUS<br>\n- DELAYED";
	prop_def  = "ASYNCHRONOUS";
	vect_data.clear();
	vect_data.push_back("ASYNCHRONOUS");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "ImageOpMode";
	prop_desc = "Define ImageOpMode for Roi/Binning/etc...  :<br>\nAvailables values :<br>\n- HardOnly<br>\n- SoftOnly<br>\n- HardAndSoft<br>";
	prop_def  = "HardAndSoft";
	vect_data.clear();
	vect_data.push_back("HardAndSoft");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "ImageSource";
	prop_desc = "Choose the source of Data given to the image attribute :<br>\n- VIDEO : use ctVideo->LastImage()<br>\n- ACQUISITION : use ctControl->ReadImage()";
	prop_def  = "VIDEO";
	vect_data.clear();
	vect_data.push_back("VIDEO");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "MemorizedAcquisitionMode";
	prop_desc = "Memorize/Define the acquisitionMode attribute at Init device<br>\nAvailables values :<br>\n- SINGLE<br>\n- ACCUMULATION<br>";
	prop_def  = "SINGLE";
	vect_data.clear();
	vect_data.push_back("SINGLE");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "MemorizedBinningH";
	prop_desc = "Memorize/Define the Binning Horizontal value of the Acquisition<br>";
	prop_def  = "1";
	vect_data.clear();
	vect_data.push_back("1");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "MemorizedBinningV";
	prop_desc = "Memorize/Define the Binning Vertical value of the Acquisition<br>";
	prop_def  = "1";
	vect_data.clear();
	vect_data.push_back("1");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "MemorizedExposureAccTime";
	prop_desc = "Memorize/Define the exposureAccTime attribute at Init device<br>";
	prop_def  = "100";
	vect_data.clear();
	vect_data.push_back("100");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "MemorizedExposureTime";
	prop_desc = "Memorize/Define the exposureTime attribute  at Init device<br>";
	prop_def  = "1000";
	vect_data.clear();
	vect_data.push_back("1000");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "MemorizedFileGeneration";
	prop_desc = "Memorize/Define the fileGeneration attribute at Init device<br>";
	prop_def  = "false";
	vect_data.clear();
	vect_data.push_back("false");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "MemorizedFileNbFrames";
	prop_desc = "";
	prop_def  = "";
	vect_data.clear();
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "MemorizedLatencyTime";
	prop_desc = "Memorize/Define the latencyTime attribute  at Init device<br>";
	prop_def  = "0";
	vect_data.clear();
	vect_data.push_back("0");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "MemorizedNbFrames";
	prop_desc = "Memorize/Define the nbFrames attribute  at Init device<br>";
	prop_def  = "1";
	vect_data.clear();
	vect_data.push_back("1");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "MemorizedRoi";
	prop_desc = "Memorize/Define the Region of Interest of the Acquisition: <br>\norigin X<br>\norigin Y<br>\nWidth<br>\nHeight<br>\n<br>\nNota:<br>\nif any roi value is <0, then we consider all detector area as Roi.";
	prop_def  = "-1\n-1\n-1\n-1";
	vect_data.clear();
	vect_data.push_back("-1");
	vect_data.push_back("-1");
	vect_data.push_back("-1");
	vect_data.push_back("-1");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "MemorizedShutterCloseTime";
	prop_desc = "Memorize/Define the shutterCloseTime attribute at Init device<br>";
	prop_def  = "1000";
	vect_data.clear();
	vect_data.push_back("1000");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "MemorizedShutterMode";
	prop_desc = "Memorize/Define the shutterMode attribute at Init device<br>\nAvailables values :<br>\n- MANUAL<br>\n- AUTO_FRAME<br>\n- AUTO_SEQUENCE";
	prop_def  = "MANUAL";
	vect_data.clear();
	vect_data.push_back("MANUAL");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "MemorizedShutterOpenTime";
	prop_desc = "Memorize/Define the shutterOpenTime attribute at Init device<br>";
	prop_def  = "1000";
	vect_data.clear();
	vect_data.push_back("1000");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "MemorizedTriggerMode";
	prop_desc = "Memorize/Define the triggerMode attribute at Init device<br>\nAvailables values :<br>\n- INTERNAL_SINGLE<br>\n- EXTERNAL_SINGLE<br>\n- EXTERNAL_MULTI<br>\n- EXTERNAL_GATE<br>\n- INTERNAL_MULTI<br>\n- EXTERNAL_START_STOP<br>\n- EXTERNAL_READOUT<br>";
	prop_def  = "INTERNAL_SINGLE";
	vect_data.clear();
	vect_data.push_back("INTERNAL_SINGLE");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "SpecialDisplayType";
	prop_desc = "Special type of the image attribute for display and saving (NOT_USED, FLOAT, ...)";
	prop_def  = "NOT_USED";
	vect_data.clear();
	vect_data.push_back("NOT_USED");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "SpoolID";
	prop_desc = "";
	prop_def  = "TO_BE_DEFINED";
	vect_data.clear();
	vect_data.push_back("TO_BE_DEFINED");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
}

//--------------------------------------------------------
/**
 *	Method      : LimaDetectorClass::write_class_property()
 *	Description : Set class description fields as property in database
 */
//--------------------------------------------------------
void LimaDetectorClass::write_class_property()
{
	//	First time, check if database used
	if (Tango::Util::_UseDb == false)
		return;

	Tango::DbData	data;
	string	classname = get_name();
	string	header;
	string::size_type	start, end;

	//	Put title
	Tango::DbDatum	title("ProjectTitle");
	string	str_title("Lima Device Generic");
	title << str_title;
	data.push_back(title);

	//	Put Description
	Tango::DbDatum	description("Description");
	vector<string>	str_desc;
	str_desc.push_back("Generic device intented to manage Detector via Lima Framework");
	description << str_desc;
	data.push_back(description);

	//  Put inheritance
	Tango::DbDatum	inher_datum("InheritedFrom");
	vector<string> inheritance;
	inheritance.push_back("TANGO_BASE_CLASS");
	inher_datum << inheritance;
	data.push_back(inher_datum);

	//	Call database and and values
	get_db_class()->put_property(data);
}

//===================================================================
//	Factory methods
//===================================================================

//--------------------------------------------------------
/**
 *	Method      : LimaDetectorClass::device_factory()
 *	Description : Create the device object(s)
 *                and store them in the device list
 */
//--------------------------------------------------------
void LimaDetectorClass::device_factory(const Tango::DevVarStringArray *devlist_ptr)
{
	/*----- PROTECTED REGION ID(LimaDetectorClass::device_factory_before) ENABLED START -----*/
	
	//	Add your own code

	//	Create devices and add it into the device list
	for (unsigned long i=0 ; i<devlist_ptr->length() ; i++)
	{
		cout4 << "Device name : " << (*devlist_ptr)[i].in() << endl;
		device_list.push_back(new LimaDetector(this, (*devlist_ptr)[i]));							 
	}

	//	Manage dynamic attributes if any
	//erase_dynamic_attributes(devlist_ptr, get_class_attr()->get_attr_list());

	//	Export devices to the outside world
	for (unsigned long i=1 ; i<=devlist_ptr->length() ; i++)
	{
		//	Add dynamic attributes if any
		LimaDetector *dev = static_cast<LimaDetector *>(device_list[device_list.size()-i]);
		dev->add_dynamic_attributes();

		//	Check before if database used.
		if ((Tango::Util::_UseDb == true) && (Tango::Util::_FileDb == false))
			export_device(dev);
		else
			export_device(dev, dev->get_name().c_str());
	}

	return;
	
	/*----- PROTECTED REGION END -----*/	//	LimaDetectorClass::device_factory_before

	//	Create devices and add it into the device list
	for (unsigned long i=0 ; i<devlist_ptr->length() ; i++)
	{
		cout4 << "Device name : " << (*devlist_ptr)[i].in() << endl;
		device_list.push_back(new LimaDetector(this, (*devlist_ptr)[i]));
	}

	//	Manage dynamic attributes if any
	erase_dynamic_attributes(devlist_ptr, get_class_attr()->get_attr_list());

	//	Export devices to the outside world
	for (unsigned long i=1 ; i<=devlist_ptr->length() ; i++)
	{
		//	Add dynamic attributes if any
		LimaDetector *dev = static_cast<LimaDetector *>(device_list[device_list.size()-i]);
		dev->add_dynamic_attributes();

		//	Check before if database used.
		if ((Tango::Util::_UseDb == true) && (Tango::Util::_FileDb == false))
			export_device(dev);
		else
			export_device(dev, dev->get_name().c_str());
	}

	/*----- PROTECTED REGION ID(LimaDetectorClass::device_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	LimaDetectorClass::device_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : LimaDetectorClass::attribute_factory()
 *	Description : Create the attribute object(s)
 *                and store them in the attribute list
 */
//--------------------------------------------------------
void LimaDetectorClass::attribute_factory(vector<Tango::Attr *> &att_list)
{
	/*----- PROTECTED REGION ID(LimaDetectorClass::attribute_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	LimaDetectorClass::attribute_factory_before
	//	Attribute : detectorDescription
	detectorDescriptionAttrib	*detectordescription = new detectorDescriptionAttrib();
	Tango::UserDefaultAttrProp	detectordescription_prop;
	detectordescription_prop.set_description("Detector user-defined text to identify the engine.");
	//	label	not set for detectorDescription
	//	unit	not set for detectorDescription
	//	standard_unit	not set for detectorDescription
	//	display_unit	not set for detectorDescription
	//	format	not set for detectorDescription
	//	max_value	not set for detectorDescription
	//	min_value	not set for detectorDescription
	//	max_alarm	not set for detectorDescription
	//	min_alarm	not set for detectorDescription
	//	max_warning	not set for detectorDescription
	//	min_warning	not set for detectorDescription
	//	delta_t	not set for detectorDescription
	//	delta_val	not set for detectorDescription
	
	detectordescription->set_default_properties(detectordescription_prop);
	//	Not Polled
	detectordescription->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(detectordescription);

	//	Attribute : detectorType
	detectorTypeAttrib	*detectortype = new detectorTypeAttrib();
	Tango::UserDefaultAttrProp	detectortype_prop;
	detectortype_prop.set_description("Return the type of the Detector.");
	//	label	not set for detectorType
	//	unit	not set for detectorType
	//	standard_unit	not set for detectorType
	//	display_unit	not set for detectorType
	//	format	not set for detectorType
	//	max_value	not set for detectorType
	//	min_value	not set for detectorType
	//	max_alarm	not set for detectorType
	//	min_alarm	not set for detectorType
	//	max_warning	not set for detectorType
	//	min_warning	not set for detectorType
	//	delta_t	not set for detectorType
	//	delta_val	not set for detectorType
	
	detectortype->set_default_properties(detectortype_prop);
	//	Not Polled
	detectortype->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(detectortype);

	//	Attribute : detectorModel
	detectorModelAttrib	*detectormodel = new detectorModelAttrib();
	Tango::UserDefaultAttrProp	detectormodel_prop;
	detectormodel_prop.set_description("Return the model of the Detector.");
	//	label	not set for detectorModel
	//	unit	not set for detectorModel
	//	standard_unit	not set for detectorModel
	//	display_unit	not set for detectorModel
	//	format	not set for detectorModel
	//	max_value	not set for detectorModel
	//	min_value	not set for detectorModel
	//	max_alarm	not set for detectorModel
	//	min_alarm	not set for detectorModel
	//	max_warning	not set for detectorModel
	//	min_warning	not set for detectorModel
	//	delta_t	not set for detectorModel
	//	delta_val	not set for detectorModel
	
	detectormodel->set_default_properties(detectormodel_prop);
	//	Not Polled
	detectormodel->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(detectormodel);

	//	Attribute : detectorWidthMax
	detectorWidthMaxAttrib	*detectorwidthmax = new detectorWidthMaxAttrib();
	Tango::UserDefaultAttrProp	detectorwidthmax_prop;
	detectorwidthmax_prop.set_description("Maximum width");
	//	label	not set for detectorWidthMax
	detectorwidthmax_prop.set_unit(" ");
	//	standard_unit	not set for detectorWidthMax
	//	display_unit	not set for detectorWidthMax
	detectorwidthmax_prop.set_format("%6d");
	//	max_value	not set for detectorWidthMax
	//	min_value	not set for detectorWidthMax
	//	max_alarm	not set for detectorWidthMax
	//	min_alarm	not set for detectorWidthMax
	//	max_warning	not set for detectorWidthMax
	//	min_warning	not set for detectorWidthMax
	//	delta_t	not set for detectorWidthMax
	//	delta_val	not set for detectorWidthMax
	
	detectorwidthmax->set_default_properties(detectorwidthmax_prop);
	//	Not Polled
	detectorwidthmax->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(detectorwidthmax);

	//	Attribute : detectorHeightMax
	detectorHeightMaxAttrib	*detectorheightmax = new detectorHeightMaxAttrib();
	Tango::UserDefaultAttrProp	detectorheightmax_prop;
	detectorheightmax_prop.set_description("Maximum height");
	//	label	not set for detectorHeightMax
	detectorheightmax_prop.set_unit(" ");
	//	standard_unit	not set for detectorHeightMax
	//	display_unit	not set for detectorHeightMax
	detectorheightmax_prop.set_format("%6d");
	//	max_value	not set for detectorHeightMax
	//	min_value	not set for detectorHeightMax
	//	max_alarm	not set for detectorHeightMax
	//	min_alarm	not set for detectorHeightMax
	//	max_warning	not set for detectorHeightMax
	//	min_warning	not set for detectorHeightMax
	//	delta_t	not set for detectorHeightMax
	//	delta_val	not set for detectorHeightMax
	
	detectorheightmax->set_default_properties(detectorheightmax_prop);
	//	Not Polled
	detectorheightmax->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(detectorheightmax);

	//	Attribute : detectorPixelDepth
	detectorPixelDepthAttrib	*detectorpixeldepth = new detectorPixelDepthAttrib();
	Tango::UserDefaultAttrProp	detectorpixeldepth_prop;
	detectorpixeldepth_prop.set_description("Pixel resolution in bits:<br>\n8<br>\n16<br>\n32<br>");
	//	label	not set for detectorPixelDepth
	detectorpixeldepth_prop.set_unit(" ");
	detectorpixeldepth_prop.set_standard_unit(" ");
	detectorpixeldepth_prop.set_display_unit(" ");
	detectorpixeldepth_prop.set_format("%6d");
	//	max_value	not set for detectorPixelDepth
	//	min_value	not set for detectorPixelDepth
	//	max_alarm	not set for detectorPixelDepth
	//	min_alarm	not set for detectorPixelDepth
	//	max_warning	not set for detectorPixelDepth
	//	min_warning	not set for detectorPixelDepth
	//	delta_t	not set for detectorPixelDepth
	//	delta_val	not set for detectorPixelDepth
	
	detectorpixeldepth->set_default_properties(detectorpixeldepth_prop);
	//	Not Polled
	detectorpixeldepth->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(detectorpixeldepth);

	//	Attribute : binnedWidthMax
	binnedWidthMaxAttrib	*binnedwidthmax = new binnedWidthMaxAttrib();
	Tango::UserDefaultAttrProp	binnedwidthmax_prop;
	binnedwidthmax_prop.set_description("Detector max width taking into account the current Horizontal Binning.");
	//	label	not set for binnedWidthMax
	binnedwidthmax_prop.set_unit(" ");
	binnedwidthmax_prop.set_standard_unit(" ");
	binnedwidthmax_prop.set_display_unit(" ");
	binnedwidthmax_prop.set_format("%6d");
	//	max_value	not set for binnedWidthMax
	//	min_value	not set for binnedWidthMax
	//	max_alarm	not set for binnedWidthMax
	//	min_alarm	not set for binnedWidthMax
	//	max_warning	not set for binnedWidthMax
	//	min_warning	not set for binnedWidthMax
	//	delta_t	not set for binnedWidthMax
	//	delta_val	not set for binnedWidthMax
	
	binnedwidthmax->set_default_properties(binnedwidthmax_prop);
	//	Not Polled
	binnedwidthmax->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(binnedwidthmax);

	//	Attribute : binnedHeightMax
	binnedHeightMaxAttrib	*binnedheightmax = new binnedHeightMaxAttrib();
	Tango::UserDefaultAttrProp	binnedheightmax_prop;
	binnedheightmax_prop.set_description("Detector max width taking into account the current Vertical Binning.");
	//	label	not set for binnedHeightMax
	binnedheightmax_prop.set_unit(" ");
	binnedheightmax_prop.set_standard_unit(" ");
	binnedheightmax_prop.set_display_unit(" ");
	binnedheightmax_prop.set_format("%6d");
	//	max_value	not set for binnedHeightMax
	//	min_value	not set for binnedHeightMax
	//	max_alarm	not set for binnedHeightMax
	//	min_alarm	not set for binnedHeightMax
	//	max_warning	not set for binnedHeightMax
	//	min_warning	not set for binnedHeightMax
	//	delta_t	not set for binnedHeightMax
	//	delta_val	not set for binnedHeightMax
	
	binnedheightmax->set_default_properties(binnedheightmax_prop);
	//	Not Polled
	binnedheightmax->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(binnedheightmax);

	//	Attribute : triggerMode
	triggerModeAttrib	*triggermode = new triggerModeAttrib();
	Tango::UserDefaultAttrProp	triggermode_prop;
	triggermode_prop.set_description("Available Trigger Modes :<br>\nINTERNAL_SINGLE<br>\nEXTERNAL_SINGLE<br>\nEXTERNAL_MULTI<br>\nEXTERNAL_GATE<br>\nINTERNAL_MULTI<br>\nEXTERNAL_START_STOP<br>\nEXTERNAL_READOUT<br>");
	//	label	not set for triggerMode
	triggermode_prop.set_unit(" ");
	//	standard_unit	not set for triggerMode
	//	display_unit	not set for triggerMode
	//	format	not set for triggerMode
	//	max_value	not set for triggerMode
	//	min_value	not set for triggerMode
	//	max_alarm	not set for triggerMode
	//	min_alarm	not set for triggerMode
	//	max_warning	not set for triggerMode
	//	min_warning	not set for triggerMode
	//	delta_t	not set for triggerMode
	//	delta_val	not set for triggerMode
	
	triggermode->set_default_properties(triggermode_prop);
	//	Not Polled
	triggermode->set_disp_level(Tango::OPERATOR);
	triggermode->set_memorized();
	triggermode->set_memorized_init(false);
	att_list.push_back(triggermode);

	//	Attribute : acquisitionMode
	acquisitionModeAttrib	*acquisitionmode = new acquisitionModeAttrib();
	Tango::UserDefaultAttrProp	acquisitionmode_prop;
	acquisitionmode_prop.set_description("Available Acquisition Modes :<br>\nSINGLE<br>\nACCUMULATION<br>\n");
	//	label	not set for acquisitionMode
	acquisitionmode_prop.set_unit(" ");
	//	standard_unit	not set for acquisitionMode
	//	display_unit	not set for acquisitionMode
	//	format	not set for acquisitionMode
	//	max_value	not set for acquisitionMode
	//	min_value	not set for acquisitionMode
	//	max_alarm	not set for acquisitionMode
	//	min_alarm	not set for acquisitionMode
	//	max_warning	not set for acquisitionMode
	//	min_warning	not set for acquisitionMode
	//	delta_t	not set for acquisitionMode
	//	delta_val	not set for acquisitionMode
	
	acquisitionmode->set_default_properties(acquisitionmode_prop);
	//	Not Polled
	acquisitionmode->set_disp_level(Tango::OPERATOR);
	acquisitionmode->set_memorized();
	acquisitionmode->set_memorized_init(false);
	att_list.push_back(acquisitionmode);

	//	Attribute : exposureTime
	exposureTimeAttrib	*exposuretime = new exposureTimeAttrib();
	Tango::UserDefaultAttrProp	exposuretime_prop;
	exposuretime_prop.set_description("Set/Get exposure time (in ms).<br>\nNota : <br>\nIn video mode (acquisition launched by Start), exposure time can be changed during acquistion.");
	//	label	not set for exposureTime
	exposuretime_prop.set_unit("ms");
	exposuretime_prop.set_standard_unit("ms");
	exposuretime_prop.set_display_unit("ms");
	exposuretime_prop.set_format("%7.2f");
	//	max_value	not set for exposureTime
	//	min_value	not set for exposureTime
	//	max_alarm	not set for exposureTime
	//	min_alarm	not set for exposureTime
	//	max_warning	not set for exposureTime
	//	min_warning	not set for exposureTime
	//	delta_t	not set for exposureTime
	//	delta_val	not set for exposureTime
	
	exposuretime->set_default_properties(exposuretime_prop);
	//	Not Polled
	exposuretime->set_disp_level(Tango::OPERATOR);
	exposuretime->set_memorized();
	exposuretime->set_memorized_init(false);
	att_list.push_back(exposuretime);

	//	Attribute : latencyTime
	latencyTimeAttrib	*latencytime = new latencyTimeAttrib();
	Tango::UserDefaultAttrProp	latencytime_prop;
	latencytime_prop.set_description("Set/Get latency time (in ms).<br>");
	//	label	not set for latencyTime
	latencytime_prop.set_unit("ms");
	latencytime_prop.set_standard_unit("ms");
	latencytime_prop.set_display_unit("ms");
	latencytime_prop.set_format("%7.2f");
	//	max_value	not set for latencyTime
	//	min_value	not set for latencyTime
	//	max_alarm	not set for latencyTime
	//	min_alarm	not set for latencyTime
	//	max_warning	not set for latencyTime
	//	min_warning	not set for latencyTime
	//	delta_t	not set for latencyTime
	//	delta_val	not set for latencyTime
	
	latencytime->set_default_properties(latencytime_prop);
	//	Not Polled
	latencytime->set_disp_level(Tango::OPERATOR);
	latencytime->set_memorized();
	latencytime->set_memorized_init(false);
	att_list.push_back(latencytime);

	//	Attribute : frameRate
	frameRateAttrib	*framerate = new frameRateAttrib();
	Tango::UserDefaultAttrProp	framerate_prop;
	//	description	not set for frameRate
	//	label	not set for frameRate
	framerate_prop.set_unit("frame/s");
	framerate_prop.set_standard_unit("frame/s");
	framerate_prop.set_display_unit("frame/s");
	framerate_prop.set_format("%7.2f");
	//	max_value	not set for frameRate
	//	min_value	not set for frameRate
	//	max_alarm	not set for frameRate
	//	min_alarm	not set for frameRate
	//	max_warning	not set for frameRate
	//	min_warning	not set for frameRate
	//	delta_t	not set for frameRate
	//	delta_val	not set for frameRate
	
	framerate->set_default_properties(framerate_prop);
	//	Not Polled
	framerate->set_disp_level(Tango::EXPERT);
	framerate->set_memorized();
	framerate->set_memorized_init(false);
	att_list.push_back(framerate);

	//	Attribute : roiX
	roiXAttrib	*roix = new roiXAttrib();
	Tango::UserDefaultAttrProp	roix_prop;
	roix_prop.set_description("Region of Interest . (Origin X)");
	//	label	not set for roiX
	roix_prop.set_unit(" ");
	//	standard_unit	not set for roiX
	//	display_unit	not set for roiX
	roix_prop.set_format("%6d");
	//	max_value	not set for roiX
	//	min_value	not set for roiX
	//	max_alarm	not set for roiX
	//	min_alarm	not set for roiX
	//	max_warning	not set for roiX
	//	min_warning	not set for roiX
	//	delta_t	not set for roiX
	//	delta_val	not set for roiX
	
	roix->set_default_properties(roix_prop);
	//	Not Polled
	roix->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(roix);

	//	Attribute : roiY
	roiYAttrib	*roiy = new roiYAttrib();
	Tango::UserDefaultAttrProp	roiy_prop;
	roiy_prop.set_description("Region of Interest . (Origin Y)");
	//	label	not set for roiY
	roiy_prop.set_unit(" ");
	//	standard_unit	not set for roiY
	//	display_unit	not set for roiY
	roiy_prop.set_format("%6d");
	//	max_value	not set for roiY
	//	min_value	not set for roiY
	//	max_alarm	not set for roiY
	//	min_alarm	not set for roiY
	//	max_warning	not set for roiY
	//	min_warning	not set for roiY
	//	delta_t	not set for roiY
	//	delta_val	not set for roiY
	
	roiy->set_default_properties(roiy_prop);
	//	Not Polled
	roiy->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(roiy);

	//	Attribute : roiWidth
	roiWidthAttrib	*roiwidth = new roiWidthAttrib();
	Tango::UserDefaultAttrProp	roiwidth_prop;
	roiwidth_prop.set_description("Region of Interest . (Width)");
	//	label	not set for roiWidth
	roiwidth_prop.set_unit(" ");
	//	standard_unit	not set for roiWidth
	//	display_unit	not set for roiWidth
	roiwidth_prop.set_format("%6d");
	//	max_value	not set for roiWidth
	//	min_value	not set for roiWidth
	//	max_alarm	not set for roiWidth
	//	min_alarm	not set for roiWidth
	//	max_warning	not set for roiWidth
	//	min_warning	not set for roiWidth
	//	delta_t	not set for roiWidth
	//	delta_val	not set for roiWidth
	
	roiwidth->set_default_properties(roiwidth_prop);
	//	Not Polled
	roiwidth->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(roiwidth);

	//	Attribute : roiHeight
	roiHeightAttrib	*roiheight = new roiHeightAttrib();
	Tango::UserDefaultAttrProp	roiheight_prop;
	roiheight_prop.set_description("Region of Interest . (Height)");
	//	label	not set for roiHeight
	roiheight_prop.set_unit(" ");
	//	standard_unit	not set for roiHeight
	//	display_unit	not set for roiHeight
	roiheight_prop.set_format("%6d");
	//	max_value	not set for roiHeight
	//	min_value	not set for roiHeight
	//	max_alarm	not set for roiHeight
	//	min_alarm	not set for roiHeight
	//	max_warning	not set for roiHeight
	//	min_warning	not set for roiHeight
	//	delta_t	not set for roiHeight
	//	delta_val	not set for roiHeight
	
	roiheight->set_default_properties(roiheight_prop);
	//	Not Polled
	roiheight->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(roiheight);

	//	Attribute : binningH
	binningHAttrib	*binningh = new binningHAttrib();
	Tango::UserDefaultAttrProp	binningh_prop;
	binningh_prop.set_description("Current Binning Horizontal value");
	//	label	not set for binningH
	binningh_prop.set_unit(" ");
	//	standard_unit	not set for binningH
	//	display_unit	not set for binningH
	binningh_prop.set_format("%6d");
	//	max_value	not set for binningH
	//	min_value	not set for binningH
	//	max_alarm	not set for binningH
	//	min_alarm	not set for binningH
	//	max_warning	not set for binningH
	//	min_warning	not set for binningH
	//	delta_t	not set for binningH
	//	delta_val	not set for binningH
	
	binningh->set_default_properties(binningh_prop);
	//	Not Polled
	binningh->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(binningh);

	//	Attribute : binningV
	binningVAttrib	*binningv = new binningVAttrib();
	Tango::UserDefaultAttrProp	binningv_prop;
	binningv_prop.set_description("Current Binning Vertical value");
	//	label	not set for binningV
	binningv_prop.set_unit(" ");
	//	standard_unit	not set for binningV
	//	display_unit	not set for binningV
	binningv_prop.set_format("%6d");
	//	max_value	not set for binningV
	//	min_value	not set for binningV
	//	max_alarm	not set for binningV
	//	min_alarm	not set for binningV
	//	max_warning	not set for binningV
	//	min_warning	not set for binningV
	//	delta_t	not set for binningV
	//	delta_val	not set for binningV
	
	binningv->set_default_properties(binningv_prop);
	//	Not Polled
	binningv->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(binningv);

	//	Attribute : nbFrames
	nbFramesAttrib	*nbframes = new nbFramesAttrib();
	Tango::UserDefaultAttrProp	nbframes_prop;
	nbframes_prop.set_description("Define the number of frames to acquire.<br>\nAvailable only in acqusisition mode, i.e SNAP.<br>\nIn live mode, i.e START it is forced to 0, this means that we request an infinite number of frames.");
	//	label	not set for nbFrames
	nbframes_prop.set_unit(" ");
	nbframes_prop.set_standard_unit(" ");
	nbframes_prop.set_display_unit(" ");
	nbframes_prop.set_format("%6d");
	//	max_value	not set for nbFrames
	//	min_value	not set for nbFrames
	//	max_alarm	not set for nbFrames
	//	min_alarm	not set for nbFrames
	//	max_warning	not set for nbFrames
	//	min_warning	not set for nbFrames
	//	delta_t	not set for nbFrames
	//	delta_val	not set for nbFrames
	
	nbframes->set_default_properties(nbframes_prop);
	//	Not Polled
	nbframes->set_disp_level(Tango::OPERATOR);
	nbframes->set_memorized();
	nbframes->set_memorized_init(false);
	att_list.push_back(nbframes);

	//	Attribute : currentFrame
	currentFrameAttrib	*currentframe = new currentFrameAttrib();
	Tango::UserDefaultAttrProp	currentframe_prop;
	currentframe_prop.set_description("Display the current frame number.");
	//	label	not set for currentFrame
	currentframe_prop.set_unit(" ");
	currentframe_prop.set_standard_unit(" ");
	currentframe_prop.set_display_unit(" ");
	currentframe_prop.set_format("%6d");
	//	max_value	not set for currentFrame
	//	min_value	not set for currentFrame
	//	max_alarm	not set for currentFrame
	//	min_alarm	not set for currentFrame
	//	max_warning	not set for currentFrame
	//	min_warning	not set for currentFrame
	//	delta_t	not set for currentFrame
	//	delta_val	not set for currentFrame
	
	currentframe->set_default_properties(currentframe_prop);
	//	Not Polled
	currentframe->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(currentframe);

	//	Attribute : fileGeneration
	fileGenerationAttrib	*filegeneration = new fileGenerationAttrib();
	Tango::UserDefaultAttrProp	filegeneration_prop;
	filegeneration_prop.set_description("Allow to save grabbed frames into a file on disk.<br>\nAvailable formats for the file are:  EDF, RAW, NXS<br>\nThe format is fixed in FileFormat property.<br>");
	//	label	not set for fileGeneration
	filegeneration_prop.set_unit(" ");
	//	standard_unit	not set for fileGeneration
	//	display_unit	not set for fileGeneration
	//	format	not set for fileGeneration
	//	max_value	not set for fileGeneration
	//	min_value	not set for fileGeneration
	//	max_alarm	not set for fileGeneration
	//	min_alarm	not set for fileGeneration
	//	max_warning	not set for fileGeneration
	//	min_warning	not set for fileGeneration
	//	delta_t	not set for fileGeneration
	//	delta_val	not set for fileGeneration
	
	filegeneration->set_default_properties(filegeneration_prop);
	//	Not Polled
	filegeneration->set_disp_level(Tango::EXPERT);
	filegeneration->set_memorized();
	filegeneration->set_memorized_init(false);
	att_list.push_back(filegeneration);

	//	Attribute : fileFormat
	fileFormatAttrib	*fileformat = new fileFormatAttrib();
	Tango::UserDefaultAttrProp	fileformat_prop;
	fileformat_prop.set_description("File format that will be used for saving.\nAvailable format are:\n- NXS\n- EDF\n- RAW\n- HDF5");
	//	label	not set for fileFormat
	fileformat_prop.set_unit(" ");
	//	standard_unit	not set for fileFormat
	//	display_unit	not set for fileFormat
	//	format	not set for fileFormat
	//	max_value	not set for fileFormat
	//	min_value	not set for fileFormat
	//	max_alarm	not set for fileFormat
	//	min_alarm	not set for fileFormat
	//	max_warning	not set for fileFormat
	//	min_warning	not set for fileFormat
	//	delta_t	not set for fileFormat
	//	delta_val	not set for fileFormat
	
	fileformat->set_default_properties(fileformat_prop);
	//	Not Polled
	fileformat->set_disp_level(Tango::EXPERT);
	fileformat->set_memorized();
	fileformat->set_memorized_init(false);
	att_list.push_back(fileformat);

	//	Attribute : filePrefix
	filePrefixAttrib	*fileprefix = new filePrefixAttrib();
	Tango::UserDefaultAttrProp	fileprefix_prop;
	//	description	not set for filePrefix
	//	label	not set for filePrefix
	fileprefix_prop.set_unit(" ");
	//	standard_unit	not set for filePrefix
	//	display_unit	not set for filePrefix
	//	format	not set for filePrefix
	//	max_value	not set for filePrefix
	//	min_value	not set for filePrefix
	//	max_alarm	not set for filePrefix
	//	min_alarm	not set for filePrefix
	//	max_warning	not set for filePrefix
	//	min_warning	not set for filePrefix
	//	delta_t	not set for filePrefix
	//	delta_val	not set for filePrefix
	
	fileprefix->set_default_properties(fileprefix_prop);
	//	Not Polled
	fileprefix->set_disp_level(Tango::EXPERT);
	fileprefix->set_memorized();
	fileprefix->set_memorized_init(false);
	att_list.push_back(fileprefix);

	//	Attribute : fileTargetPath
	fileTargetPathAttrib	*filetargetpath = new fileTargetPathAttrib();
	Tango::UserDefaultAttrProp	filetargetpath_prop;
	//	description	not set for fileTargetPath
	//	label	not set for fileTargetPath
	filetargetpath_prop.set_unit(" ");
	//	standard_unit	not set for fileTargetPath
	//	display_unit	not set for fileTargetPath
	//	format	not set for fileTargetPath
	//	max_value	not set for fileTargetPath
	//	min_value	not set for fileTargetPath
	//	max_alarm	not set for fileTargetPath
	//	min_alarm	not set for fileTargetPath
	//	max_warning	not set for fileTargetPath
	//	min_warning	not set for fileTargetPath
	//	delta_t	not set for fileTargetPath
	//	delta_val	not set for fileTargetPath
	
	filetargetpath->set_default_properties(filetargetpath_prop);
	//	Not Polled
	filetargetpath->set_disp_level(Tango::EXPERT);
	filetargetpath->set_memorized();
	filetargetpath->set_memorized_init(false);
	att_list.push_back(filetargetpath);

	//	Attribute : fileNbFrames
	fileNbFramesAttrib	*filenbframes = new fileNbFramesAttrib();
	Tango::UserDefaultAttrProp	filenbframes_prop;
	//	description	not set for fileNbFrames
	//	label	not set for fileNbFrames
	filenbframes_prop.set_unit(" ");
	//	standard_unit	not set for fileNbFrames
	//	display_unit	not set for fileNbFrames
	//	format	not set for fileNbFrames
	//	max_value	not set for fileNbFrames
	//	min_value	not set for fileNbFrames
	//	max_alarm	not set for fileNbFrames
	//	min_alarm	not set for fileNbFrames
	//	max_warning	not set for fileNbFrames
	//	min_warning	not set for fileNbFrames
	//	delta_t	not set for fileNbFrames
	//	delta_val	not set for fileNbFrames
	
	filenbframes->set_default_properties(filenbframes_prop);
	//	Not Polled
	filenbframes->set_disp_level(Tango::EXPERT);
	filenbframes->set_memorized();
	filenbframes->set_memorized_init(false);
	att_list.push_back(filenbframes);

	//	Attribute : fileExtension
	fileExtensionAttrib	*fileextension = new fileExtensionAttrib();
	Tango::UserDefaultAttrProp	fileextension_prop;
	fileextension_prop.set_description("Display the actual extension that will be used for saving files, according to the chosen file format");
	//	label	not set for fileExtension
	fileextension_prop.set_unit(" ");
	//	standard_unit	not set for fileExtension
	//	display_unit	not set for fileExtension
	//	format	not set for fileExtension
	//	max_value	not set for fileExtension
	//	min_value	not set for fileExtension
	//	max_alarm	not set for fileExtension
	//	min_alarm	not set for fileExtension
	//	max_warning	not set for fileExtension
	//	min_warning	not set for fileExtension
	//	delta_t	not set for fileExtension
	//	delta_val	not set for fileExtension
	
	fileextension->set_default_properties(fileextension_prop);
	//	Not Polled
	fileextension->set_disp_level(Tango::EXPERT);
	//	Not Memorized
	att_list.push_back(fileextension);

	//	Attribute : operationsList
	operationsListAttrib	*operationslist = new operationsListAttrib();
	Tango::UserDefaultAttrProp	operationslist_prop;
	operationslist_prop.set_description("Enumerate all active 'post processing' operations on the image.");
	//	label	not set for operationsList
	operationslist_prop.set_unit(" ");
	operationslist_prop.set_standard_unit(" ");
	operationslist_prop.set_display_unit(" ");
	//	format	not set for operationsList
	//	max_value	not set for operationsList
	//	min_value	not set for operationsList
	//	max_alarm	not set for operationsList
	//	min_alarm	not set for operationsList
	//	max_warning	not set for operationsList
	//	min_warning	not set for operationsList
	//	delta_t	not set for operationsList
	//	delta_val	not set for operationsList
	
	operationslist->set_default_properties(operationslist_prop);
	//	Not Polled
	operationslist->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(operationslist);


	//	Create a list of static attributes
	create_static_attribute_list(get_class_attr()->get_attr_list());
	/*----- PROTECTED REGION ID(LimaDetectorClass::attribute_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	LimaDetectorClass::attribute_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : LimaDetectorClass::pipe_factory()
 *	Description : Create the pipe object(s)
 *                and store them in the pipe list
 */
//--------------------------------------------------------
void LimaDetectorClass::pipe_factory()
{
	/*----- PROTECTED REGION ID(LimaDetectorClass::pipe_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	LimaDetectorClass::pipe_factory_before
	/*----- PROTECTED REGION ID(LimaDetectorClass::pipe_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	LimaDetectorClass::pipe_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : LimaDetectorClass::command_factory()
 *	Description : Create the command object(s)
 *                and store them in the command list
 */
//--------------------------------------------------------
void LimaDetectorClass::command_factory()
{
	/*----- PROTECTED REGION ID(LimaDetectorClass::command_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	LimaDetectorClass::command_factory_before


	//	Command Prepare
	PrepareClass	*pPrepareCmd =
		new PrepareClass("Prepare",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pPrepareCmd);

	//	Command Snap
	SnapClass	*pSnapCmd =
		new SnapClass("Snap",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pSnapCmd);

	//	Command Start
	StartClass	*pStartCmd =
		new StartClass("Start",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pStartCmd);

	//	Command Stop
	StopClass	*pStopCmd =
		new StopClass("Stop",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pStopCmd);

	//	Command SetROI
	SetROIClass	*pSetROICmd =
		new SetROIClass("SetROI",
			Tango::DEVVAR_ULONGARRAY, Tango::DEV_VOID,
			"[origin_x, origin_y, width, height]",
			"",
			Tango::OPERATOR);
	command_list.push_back(pSetROICmd);

	//	Command SetBinning
	SetBinningClass	*pSetBinningCmd =
		new SetBinningClass("SetBinning",
			Tango::DEVVAR_ULONGARRAY, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pSetBinningCmd);

	//	Command ResetBinning
	ResetBinningClass	*pResetBinningCmd =
		new ResetBinningClass("ResetBinning",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pResetBinningCmd);

	//	Command ResetROI
	ResetROIClass	*pResetROICmd =
		new ResetROIClass("ResetROI",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pResetROICmd);

	//	Command GetAttributeAvailableValues
	GetAttributeAvailableValuesClass	*pGetAttributeAvailableValuesCmd =
		new GetAttributeAvailableValuesClass("GetAttributeAvailableValues",
			Tango::DEV_STRING, Tango::DEVVAR_STRINGARRAY,
			"Attribute name",
			"List of strings containing the available values",
			Tango::EXPERT);
	command_list.push_back(pGetAttributeAvailableValuesCmd);

	//	Command GetAvailableCapabilities
	GetAvailableCapabilitiesClass	*pGetAvailableCapabilitiesCmd =
		new GetAvailableCapabilitiesClass("GetAvailableCapabilities",
			Tango::DEV_VOID, Tango::DEVVAR_STRINGARRAY,
			"",
			"The list of available capabilities",
			Tango::OPERATOR);
	command_list.push_back(pGetAvailableCapabilitiesCmd);

	//	Command ResetFileIndex
	ResetFileIndexClass	*pResetFileIndexCmd =
		new ResetFileIndexClass("ResetFileIndex",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::EXPERT);
	command_list.push_back(pResetFileIndexCmd);

	//	Command ReloadROI
	ReloadROIClass	*pReloadROICmd =
		new ReloadROIClass("ReloadROI",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pReloadROICmd);

	//	Command GetDataStreams
	GetDataStreamsClass	*pGetDataStreamsCmd =
		new GetDataStreamsClass("GetDataStreams",
			Tango::DEV_VOID, Tango::DEVVAR_STRINGARRAY,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pGetDataStreamsCmd);

	//	Command InitInterface
	InitInterfaceClass	*pInitInterfaceCmd =
		new InitInterfaceClass("InitInterface",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::EXPERT);
	command_list.push_back(pInitInterfaceCmd);

	/*----- PROTECTED REGION ID(LimaDetectorClass::command_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	LimaDetectorClass::command_factory_after
}

//===================================================================
//	Dynamic attributes related methods
//===================================================================

//--------------------------------------------------------
/**
 * method : 		LimaDetectorClass::create_static_attribute_list
 * description : 	Create the a list of static attributes
 *
 * @param	att_list	the ceated attribute list
 */
//--------------------------------------------------------
void LimaDetectorClass::create_static_attribute_list(vector<Tango::Attr *> &att_list)
{
	for (unsigned long i=0 ; i<att_list.size() ; i++)
	{
		string att_name(att_list[i]->get_name());
		transform(att_name.begin(), att_name.end(), att_name.begin(), ::tolower);
		defaultAttList.push_back(att_name);
	}

	cout2 << defaultAttList.size() << " attributes in default list" << endl;

	/*----- PROTECTED REGION ID(LimaDetectorClass::create_static_att_list) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LimaDetectorClass::create_static_att_list
}


//--------------------------------------------------------
/**
 * method : 		LimaDetectorClass::erase_dynamic_attributes
 * description : 	delete the dynamic attributes if any.
 *
 * @param	devlist_ptr	the device list pointer
 * @param	list of all attributes
 */
//--------------------------------------------------------
void LimaDetectorClass::erase_dynamic_attributes(const Tango::DevVarStringArray *devlist_ptr, vector<Tango::Attr *> &att_list)
{
	Tango::Util *tg = Tango::Util::instance();

	for (unsigned long i=0 ; i<devlist_ptr->length() ; i++)
	{
		Tango::DeviceImpl *dev_impl = tg->get_device_by_name(((string)(*devlist_ptr)[i]).c_str());
		LimaDetector *dev = static_cast<LimaDetector *> (dev_impl);

		vector<Tango::Attribute *> &dev_att_list = dev->get_device_attr()->get_attribute_list();
		vector<Tango::Attribute *>::iterator ite_att;
		for (ite_att=dev_att_list.begin() ; ite_att != dev_att_list.end() ; ++ite_att)
		{
			string att_name((*ite_att)->get_name_lower());
			if ((att_name == "state") || (att_name == "status"))
				continue;
			vector<string>::iterator ite_str = find(defaultAttList.begin(), defaultAttList.end(), att_name);
			if (ite_str == defaultAttList.end())
			{
				cout2 << att_name << " is a UNWANTED dynamic attribute for device " << (*devlist_ptr)[i] << endl;
				Tango::Attribute &att = dev->get_device_attr()->get_attr_by_name(att_name.c_str());
				dev->remove_attribute(att_list[att.get_attr_idx()], true, false);
				--ite_att;
			}
		}
	}
	/*----- PROTECTED REGION ID(LimaDetectorClass::erase_dynamic_attributes) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LimaDetectorClass::erase_dynamic_attributes
}

//--------------------------------------------------------
/**
 *	Method      : LimaDetectorClass::get_attr_object_by_name()
 *	Description : returns Tango::Attr * object found by name
 */
//--------------------------------------------------------
Tango::Attr *LimaDetectorClass::get_attr_object_by_name(vector<Tango::Attr *> &att_list, string attname)
{
	vector<Tango::Attr *>::iterator it;
	for (it=att_list.begin() ; it<att_list.end() ; ++it)
		if ((*it)->get_name()==attname)
			return (*it);
	//	Attr does not exist
	return NULL;
}


/*----- PROTECTED REGION ID(LimaDetectorClass::Additional Methods) ENABLED START -----*/

/*----- PROTECTED REGION END -----*/	//	LimaDetectorClass::Additional Methods
} //	namespace
